### ISSUE TITLE
data-image-src not working in mobile

### ISSUE THREAD

**Issue by jabir145** [pixelcog/parallax.js#100]
$('#hero-bloc').parallax({imageSrc: 'img/header.jpg'});

.parallax-window {
    min-height: 200px!important;
    background: transparent!important;
}

div id="hero-bloc" class="parallax-window" data-parallax="scroll" data-image-src="img/header.jpg" data-speed="0.3"

This parralax is working properly while opening pc or laptop. when i try to open in mobile devices the background image not showing.

**Comment by robbiegod** [comment]
this totally might not be helpful, but can you try setting a height: 200px !important;  and set the display type to block on that class.  Also put a space before each !important in your css.  Not sure if any of that is causing your problem, but at least it may rules some things out.  Do you have a link to your page you can post on here?

**Comment by wstoettinger** [comment]
@robbiegod is right, the parallax effect unfortunately doesn't work on mobile. the workaround which is used here, is to put a static background image.

Using both `data-image-src` and `{imageSrc: '...'}` should not be a problem here I think, as long as the same values are used, one get's overwritten by the other (don't know which one, though). 

However, using `data-parrallax="scroll"` and `$('#hero-bloc').parallax(...)` causes the parallax to initialize twice, which could cause problems and should be avoided.
