### ISSUE TITLE
parallax not scrolling

### ISSUE THREAD

**Issue by mainpart** [pixelcog/parallax.js#102]
i'm having a situation when top attribute of parallax-mirror's div is not changing while scrolling.

    $('.slide3').parallax({
    imageSrc:'https://s-media-cache-ak0.pinimg.com/736x/1e/f8/15/1ef815a3156e5ca9649eb743e4342367.jpg',
    parallax:'scroll',
    speed:0.7,
    });

but layer .slide3 never get parallaxed
i'm using chrome.
putting all landing-page here
http://rghost.ru/private/6hZFjMn98/26464f8c699c91f8c9f9ef93793ea1eb

**Comment by mainpart** [comment]
looks like my docWidth  and winWidth are always equal. so 
    var scrollTopMax  = Parallax.docHeight - Parallax.winHeight; // always 0
    Parallax.scrollTop  = Math.max(0, Math.min(scrollTopMax,  $win.scrollTop())); // max (0,min(0,whatever)) always 0

**Comment by mainpart** [comment]
solution was
<!doctype html>

**Comment by jualoppaz** [comment]
@mainpart do you know why is neccesary to set doctype in the view? I though it was setted by default.
