### ISSUE TITLE
IE issue: Incorrect position until window resize

### ISSUE THREAD

**Issue by burni** [pixelcog/parallax.js#103]
![citrus](https://cloud.githubusercontent.com/assets/3257129/11929373/4a263bb6-a7d2-11e5-8c9f-f78b57d9eb2c.jpg)

I'm getting this is in IE (specifically IE11). Until I resize the window, the image is loading high. IS there anyway to get the script to refresh itself so it recalculates after page load or anything?

The grey is the background 'under' the image - it shouldn't bee seen.

Love the script by the way - nice and easy for a dumb front end guy like me to use!

**Comment by scottblinch** [comment]
I was actually coming here with the exact same issue. Here's a live example (only occurs on IE11):

http://www.buckland.com/about/

Will look deeper and report back.

**Comment by scottblinch** [comment]
Actually, it looks like updating to the latest release (1.4 - which was literally added half an hour ago) fixes the issue for me.

**Comment by wstoettinger** [comment]
@scottblinch that's cool! i just wanted to suggest that before looking further into it. 
@burni let me know if the update fixes it for you too!

It seems that querying the window height returns empty at the time the library is loaded. And then the visibility is set to hidden.
Two questions to @mikegreiling : 
 * might there be a different event than `$(document).on('ready.px.parallax.data-api', function() )` to trigger that?
 * what was the original thought to set the visibility to hidden in the first place? performance issues?

**Comment by burni** [comment]
Yup, that fixes it for me also! That's timing! Thanks Scott :)

**Comment by carlosnpz** [comment]
I'm using version 1.4.2, and nothing you said here solved the problem. :/
