### ISSUE TITLE
New tag for 1.4.1

### ISSUE THREAD

**Issue by liviucmg** [pixelcog/parallax.js#107]
Hi guys,

Could you make a new version tag 1.4.1 for the current master? The 1.4.0 version is still missing a comma from bower.json and is not installable. See f139f5c515fa41bc12c13c15c1a979d4b7a8e5ea

Cheers,  :beers: 
Liviu

**Comment by wstoettinger** [comment]
thanks @liviucmg for pointing that out! 
my appologies for the inconveniences!

**Comment by liviucmg** [comment]
No problem @wstoettinger, thank you as well for the wonderful plugin. :) Happy Holidays!
