### ISSUE TITLE
Load callback

### ISSUE THREAD

**Issue by jptaylor** [pixelcog/parallax.js#108]
Would be really great to add a load callback for when the mirror has finished loading the image source. When using larger images it can look ugly - I want to add a background colour and fade it out after the image has finished loading in.

**Comment by wstoettinger** [comment]
thanks for your suggestion. we will look into that. 

in the meantime I can recommend to improve image loading performance with the help of this article: 
https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization?hl=en

Google pagespeed insights also gives good hints on how much you can compress images without sacrificing quality.

**Comment by nckblu** [comment]
I faced this issue too, unfortunately I can't give you exact code I've used as I don't have to hand right now but the best way to do this I think is to use an image preloader method such as something here: http://stackoverflow.com/questions/280049/javascript-callback-for-knowing-when-an-image-is-loaded

When the image is loaded you can call the plugin with the loaded image, set a timeout of something small and arbitrary (like 200ms) to allow for browser rendering time and fade out the background colour after that.

**Comment by wstoettinger** [comment]
please refer to #192
