### ISSUE TITLE
Image sizing not correct

### ISSUE THREAD

**Issue by EdwardJS** [pixelcog/parallax.js#11]
Hi
I've noticed that for whatever reason, `data-natural-height` and `data-natural-width` does not pass the values correctly and that the image displayed is really out of proportion. I'm working with a 1024x256 image, but parallax.js expands the image way out of proportion. I am using mostly default settings for testing

![parallax](https://cloud.githubusercontent.com/assets/7594042/5119940/2fe7439c-703f-11e4-9af6-756e6dfe98ea.jpg)

Image 1 is the image as loaded via parallax and image 2 is loaded without. They are both the same sized frame, but for some reason, image 1 (with parallax) is overly zoomed in. Any ideas? Or am I missing a setting?

**Comment by mikegreiling** [comment]
closing pending further feedback...
