### ISSUE TITLE
Change transform timing

### ISSUE THREAD

**Issue by Tu-Szu-Chi** [pixelcog/parallax.js#110]
**My Engilsh is not good**

---

This is my code:
```
<div  class="parallax-window"id="section-1" data-parallax="scroll" data-image-src="images/home/bg_01.png" ></div>
<div class="parallax-window" data-parallax="scroll" data-image-src="images/home/bg_02.png"></div>

```
---

In generally,when bottom of [bg_01.png] arrive at the bottom of window,[bg_02.png] will begin to expand,right?
But,I hope when [bg_01.png] arrive at the middle of window,[bg_02.png] begin to expand.
I try to change Line 161~230 in parallax.js,but I can't reach it.

**Comment by KillTheBronies** [comment]
You want to change the height of `#section-1`, either set a CSS rule or use inline styling. Something like `#section-1 {height: 50vh;}` should do what you want.

**Comment by Tu-Szu-Chi** [comment]
Thanks Bronies,But I had set the #section-1 {height:330vh} in CSS,It is not rech my effect ....
thanks you very much.

**Comment by KillTheBronies** [comment]
I'm not sure I understand what your trying to do then. Do you mean to have a gap between the two images?

**Comment by Tu-Szu-Chi** [comment]
No No,Actually,soem effect which I want can change [speed] -attribute,let it add more
but,It will let my background too big
 In fact,I let the content which I want to show to be a [background],so my content was too fast to disvisible,I hope it can disvisble when it bottom in the middle of screen 
-----------------
very thanks you to answer me,I know my English is poor

**Comment by wstoettinger** [comment]
seems solved
