### ISSUE TITLE
after resize window go white space at top

### ISSUE THREAD

**Issue by vandivicario** [pixelcog/parallax.js#112]
so i try to resize they window and then i figure that i got big white space at top of my image how i fix it
![untitled](https://cloud.githubusercontent.com/assets/16689834/12302653/d90f1e9a-ba58-11e5-853c-ed74a452d129.png).
help please senpai

**Comment by vandivicario** [comment]
heres my code
<div class="parallax-window" ></div>
<script>
   $('.parallax-window').parallax({imageSrc: 'img/paralax.jpg'});
   jQuery(window).trigger('resize').trigger('scroll');
</script>

**Comment by KillTheBronies** [comment]
Try adding this javascript somewhere. Probably not very optimised but it should work at least. 

<pre>$(window).resize(function() {
  $(window).trigger('resize.px.parallax');
});</pre>

**Comment by swthate** [comment]
I'm late to the party, but @KaelWD , thanks a million!

:beers:

**Comment by revxx14** [comment]
@KaelWD thanks so much for that! That definitely needs to be in the README.

**Comment by ses** [comment]
dont work for me :(

**Comment by ralph9** [comment]
Doesn't work for me either, you can delete `overflow: "hidden"` from the css rules in the js file, but that will make the photos overflow (huh) to the lower parallax if you have one. So far none of the solutions seem to suit me.

**Comment by wstoettinger** [comment]
please also have a look at #128.
