### ISSUE TITLE
Define parallax div inside another

### ISSUE THREAD

**Issue by jualoppaz** [pixelcog/parallax.js#121]
When I define the parallax div as a body child I can see my parallax effect working, but if I define it inside another div parallax doesn't work.

For example, the following code works very well:

> <body>

```
    <div class="parallax-window" data-parallax="scroll" data-speed="0.3" data-image-src="/img/home.jpg" data-bleed="10" data-natural-width="1400" data-natural-height="1400"></div>

    <section>
            ...
    </section>
```

</body>

But the following one doesn't work:

> <body>

```
    <div id="main-content">
            <div class="parallax-window" data-parallax="scroll" data-speed="0.3" data-image-src="/img/home.jpg" data-bleed="10" data-natural-width="1400" data-natural-height="1400"></div>
    </div>

    <section>
            ...
    </section>
```

</body>

Any idea? Thanks so much.

**Comment by TheRichCourt** [comment]
Not sure how much help this will be now, but does your 'main-content' div have a background (even just a white one or something)? It needs to be transparent, as the parallax background will be behind it I believe.

**Comment by wstoettinger** [comment]
this should not be a problem as long as the backgrounds in all divs below the window are transparent and the window must have a minimum height.
