### ISSUE TITLE
(1) On page form misbehaves (2) parallax image appears wrongly when used together with headroom.js

### ISSUE THREAD

**Issue by auroramedia** [pixelcog/parallax.js#123]
I am very fond of this plugin but am running into two issues. A test page can be viewed at http://webdemo.website/culturaldetective/who/certified-facilitators.html
This is a joomla website with a Gantry 5 template.

Issue #1 
The page navigation for the list of facilitators fails when using this plugin. Firebug shows an error 'TypeError: document.adminForm.limitstart is undefined'. The navigation works perfectly if I do not load the plugin, or if I try to use a different parallax plugin such as stellar.

Issue #2 
If I use 'headroom.js' to make the top navigation menu sticky, the parallax scroll image appears offset downwards by as many pixels as the menu height. As a result, the text and image do not overlap correctly. However, If I size the browser window once and restore it back to the full size, the issue corrects itself and the problem disappear. 

The two issues exist independent of each other.

I would be extremely thankful if these issues could be addressed, or in case a solution already exists, it would be a help if you could point me in the right direction to overcome the issues.

Thanks

**Comment by wstoettinger** [comment]
Hey @auroramedia ! I hope you found a solution to your problem already, anyways, i'll give a shot at issue number 2: have you tried adding some additional padding behind the nav bar? some people have suggested this in #128 . As of issue number 1 I really have no clue what could have gone wrong. In case there is still an issue, please provide additional information. 

It would also be great if you could post your solution, if you found one!

Cheers
