### ISSUE TITLE
Individual Image Scroll Speed

### ISSUE THREAD

**Issue by redjester** [pixelcog/parallax.js#127]
Hi - Was wondering if anybody knows a way to change the scroll speed for each image individually?

I have appended unique classes to each .parallax-mirror div, and the corresponding img tag.

Any help is appreciated!

**Comment by wstoettinger** [comment]
you can simply do this by calling the parallax function with different speed options for each image.  however, you have to use the html markup (as opposed to the data-attribute markup) and select each image individually beforehand.

eg:
```javascript
$('.parallax-window#window-1').parallax({speed:1;});
$('.parallax-window#window-2').parallax({speed:-1;});
```
