### ISSUE TITLE
Shrinking header causes a gap above parallaxed elements

### ISSUE THREAD

**Issue by revxx14** [pixelcog/parallax.js#130]
I'm trying to figure out why a gap is appearing above the parallaxed bit on [this page](http://ntsource.myweblinx.net/hosting/hybrid/). I know it's related to the shrinking header, but the solution mentioned in your README (`$(window).trigger("resize").trigger("scroll");`) doesn't seem to be working.

This is the script that resizes my header:

```
$(window).on("load scroll", function() {
    if ($(window).scrollTop() > 100 && !$("html").hasClass("-scrolled")) {
        $("html").addClass("-scrolled");
        $(window).trigger("resize").trigger("scroll");
    } else if ($(window).scrollTop() < 100 && $("html").hasClass("-scrolled")) {
        $("html").removeClass("-scrolled");
        $(window).trigger("resize").trigger("scroll");
    }
});
```

**Comment by Leobaillard** [comment]
Yep,I have the exact same problem. Has anyone found an other solution?

**Comment by revxx14** [comment]
I don't remember for sure how I fixed this, but I want to say I reinitialized the parallax once the header shrunk.

**Comment by Leobaillard** [comment]
What do you mean by reinitialized? Did you unbind it before running it again or just ran the function after the shrinking?

**Comment by revxx14** [comment]
I'm looking through the project I did this on, here's what I'm seeing:

```
$(window).on("load scroll resize", function() {
    if ($(window).scrollTop() > 100 && !$("html").hasClass("-scrolled")) {
        $("html").addClass("-scrolled");
    } else if ($(window).scrollTop() < 100 && $("html").hasClass("-scrolled")) {
        $("html").removeClass("-scrolled");
    }
    
    $(window).trigger("resize.px.parallax"); // I think this is what I did, been a while though so it's hard to remember.
});
```
