### ISSUE TITLE
Parallax without fullscreen (adapting to window.height on startup)

### ISSUE THREAD

**Issue by denbue** [pixelcog/parallax.js#131]
My parallax image should be sized to the height of the browser window on the initial page load and not set to cover. Is it possible to use this script for that purpose? Any CSS suggestions?

Thank you very much for your help!

**Comment by Showcase-Joz** [comment]
would love to know how to add parallax.js to a browser window auto resize script :) :)

**Comment by anapettirossi** [comment]
@denbue did you figure out how to implement fullscreen parallax?

**Comment by EprimePRO** [comment]
This css seems to work well @denbue @anapettirossi 
```css
.parallax-window {
    min-height: 100vh;
    background: transparent;
}
```
if you want to use jQuery use something like this.
```javascript
$(window).on('load resize', function () {
    $parallax.css('height', $(this).height());
}
```

**Comment by wstoettinger** [comment]
seems to be fixed
