### ISSUE TITLE
Bootstrap -tab- not working.

### ISSUE THREAD

**Issue by UWiX-nl** [pixelcog/parallax.js#132]
When I'm including the parallax.js script into my page header it works great. But when I'm using the bootstrap data-toggle="tab" on the same page the bootstrap tabs are not working.

No errors are returned whatsoever and the only way to make the bootstrap tabs working is by removing the loading of parallax.js script from the page(s).

Any suggestions how to fix this?

**Comment by wstoettinger** [comment]
is this still an issue with the latest version an jquery 3? is the parallax inside a tab? please check the latest version and reopen if necessary!
Also check #168 and #211
