### ISSUE TITLE
Wordpress Setup

### ISSUE THREAD

**Issue by jgacuca567** [pixelcog/parallax.js#138]
@kosvrouvas
@mikegreiling 

I reviewed the issue from #25, however my image doesn't show. 

Code I used from the example
```php
$url = wp_get_attachment_url( get_post_thumbnail_id( $post->ID ) );

<div class="parallax-window" data-parallax="scroll" data-image-src="<?php echo $url; ?>">
</div>
```
See Image Below
<img width="951" alt="screen shot 2016-04-05 at 5 52 12 pm" src="https://cloud.githubusercontent.com/assets/4000076/14299446/737fa37e-fb58-11e5-8b54-c86283bb31bf.png">

Platform
`Wordpress: 4.5`

**Comment by benfurfie** [comment]
If that code is exactly what is in your file, the first thing to do is to wrap `$url = wp_get_attachment_url( get_post_thumbnail_id( $post->ID ) );` in `<?php ?>` tags.

If you already have, have you tried echoing out $url to make sure it's not outputting NULL?

Just in case you - or anyone else who comes across this - doesn't know how to, place this under the line starting $url = ...

`<?php var_dump($url); ?>`

Check the output on the relevant page and let us know what it says.

**Comment by jgacuca567** [comment]
@benfurfie 
I got `bool(false)` for the output.

**Comment by hvsh** [comment]
Use this @jgacuca567 @benfurfie 

```
$id = get_post_thumbnail_id($post->ID);
$url = wp_get_attachment_image_src($id, 'full');

<div class="parallax-window" data-parallax="scroll" data-image-src="<?php echo $url[0]; ?>">
</div>
```

**Comment by jgacuca567** [comment]
Hi @hvsh the image is not showing, I still have `var dump` but I still get `bool false`. What can I do to ensure the image is actually posted. 

```php
$id = get_post_thumbnail_id($post->ID);
$url = wp_get_attachment_image_src($id, 'full');
var_dump($url);
```

CC @benfurfie @kosvrouvas @mikegreiling

**Comment by hvsh** [comment]
Its working fine for me. var_dump gives me 

```
array (size=4)
  0 => string 'http://imagesource.jpg'
  1 => int 1925
  2 => int 975
  3 => boolean false
```

and I use $url[0] to get image source.

**Comment by jgacuca567** [comment]
@hvsh, for the actual image, where have you placed the image?

**Comment by hvsh** [comment]
you can echo image like 

`<img src="<?php echo $url[0]; ?>">`

and for parallax.js 

```
<div class="parallax-window" data-parallax="scroll" data-image-src="<?php echo $url[0]; ?>">
</div>
```

Make sure to set height in css for .parallax window

**Comment by jgacuca567** [comment]
@hvsh, My Image is not showing. These are the steps have done so far
1. In the Wordpress Edit Page, I have added the image, 
<img width="2062" alt="screen shot 2016-04-15 at 1 07 17 pm" src="https://cloud.githubusercontent.com/assets/4000076/14569176/0876135a-030b-11e6-82e8-009d355146e5.png">

2. In my template page, the image code is posted at the top
```php
<section class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
<?php
$id = get_post_thumbnail_id($post->ID);
$url = wp_get_attachment_image_src($id, 'full');
var_dump($url);
?>
<div class="parallax-window" data-parallax="scroll" data-image-src="<?php echo esc_url($url[0]); ?>">
</div>
	<aside id="work">
		<?php
$work = new WP_Query('pagename=work');

/** The Loops */
if ($work->have_posts()) {
	while ($work->have_posts()) {
		$work->the_post();
		the_title('<h1 class="text-xs-center">', '</h1>');
		the_content();
	}
}

wp_reset_postdata();
?>
```
3. What steps did you do

**Comment by hvsh** [comment]
@jgacuca567 thats your problem. The image needs to be uploaded as a featured image. Thats why its not working.

$url[0] echos the source of the featured image. Not the image you put in the WYSIWYG editor.

**Comment by jgacuca567** [comment]
@hvsh, Ok that is working now, I am getting the array `array(4) { [0]=> string(63) "http://dosbrandingwp.dev/wp-content/uploads/2016/04/stairs2.jpg" [1]=> int(5120) [2]=> int(5120) [3]=> bool(false) }`, what should I do next for the image to show.

**Comment by hvsh** [comment]
@jgacuca567  just echo $url[0] -  That is the source of the image.

<div class="parallax-window" data-parallax="scroll" data-image-src="<?php echo $url[0]; ?>">
</div>

**Comment by jgacuca567** [comment]
Ok, so the image url is showing in the view source, but not the image. 

<img width="1821" alt="screen shot 2016-04-15 at 1 33 08 pm" src="https://cloud.githubusercontent.com/assets/4000076/14569766/b73ad490-030e-11e6-88f5-7705687c0262.png">

is there a way you can send me an example of your file so I can see what I am doing wrong.

**Comment by hvsh** [comment]
@jgacuca567 My file is on localhost  why dont you try using the below code. You dont need to put image tag with that, just set the height of .parallax-window in css and thats it. 
```
<div class="parallax-window" data-parallax="scroll" data-image-src="<?php echo $url[0]; ?>">
</div>
```

**Comment by jgacuca567** [comment]
@hvsh I am not putting the image code its coming up automatically
The 
```css
.parallax-window
``` 
has been set, but only showing in view source. I think its best if you send the file, Looks its an error that I can't see.

**Comment by hvsh** [comment]
jgacuca567 I cant send the file im working on a commercial theme. 

```
<?php
/**
 * Template part for displaying single posts.
 * @link https://codex.wordpress.org/Template_Hierarchy
 */
$id = get_post_thumbnail_id($post->ID);
$image_att = wp_get_attachment_image_src($id, 'full');

?>

<article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
**<div class="parallax-window" data-parallax="scroll" data-image-src="<?php echo esc_url($image_att[0]); ?>">**
</div>
<!-- theme specific code goes here  -->
</article>
```

**Comment by jgacuca567** [comment]
@hvsh , the image is now showing after I moved my 
```php  
$id = get_post_thumbnail_id($post->ID);
``` 
to the top of the page. That was the mistake I was making. Thank you for being patient by helping out. Truly Much Appreciated.

**Comment by hvsh** [comment]
@jgacuca567 no problem , most welcome :)
