### ISSUE TITLE
Can this work in conjunction with RoyalSlider?

### ISSUE THREAD

**Issue by leecollings** [pixelcog/parallax.js#140]
I've configured this correctly on several pages on my website, and looks fantastic.

However on the homepage, I have in place of the large full width static images, a [RoyalSlider](http://dimsemenov.com/plugins/royal-slider/wordpress/) element, running under Wordpress.

Obviously there are no static images here, but slides, so entering a static image URL in the markup will not work. Is there a way to just use the contents of the div to use as a background container?

```
<div id="slider" class="parallax-window" data-parallax="scroll">
    <?php echo get_new_royalslider(1); ?>
</div>
```

**Comment by wstoettinger** [comment]
yes, that possible. please look at the html markup in the README.
