### ISSUE TITLE
parallax-mirror remains fixed?

### ISSUE THREAD

**Issue by JohnnyWalkerDesign** [pixelcog/parallax.js#141]
I don't know what I'm doing wrong, but I can see that an element with the class parallax-mirror has been created. I can see it. I can scroll up and down my site. But the thing remains fixed (like a CSS `position: fixed`) and doesn't move at all.

HTML:
`<div class="parallax-window" data-parallax="scroll" data-position="top" data-bleed="10" data-speed="0.2" data-image-src="<?php echo $headerImage['url']; ?>"></div>`

CSS:
`.parallax-window {
  min-height: 700px;
  background: transparent;
}`

It's all working... the image appears... it just doesn't scroll when the page scrolls?

In inspector I can see this:

`<div class="parallax-mirror" style="visibility: visible; z-index: -100; position: fixed; top: 10px; left: 0px; overflow: hidden; transform: translate3d(0px, 0px, 0px); height: 720px; width: 1467px;"><img class="parallax-slider" src="http://localhost/~johnny/Dropbox/Work/Work/LimitedSpace/www-LS/wp-content/uploads/2016/04/Homepage-Header.jpg" style="transform: translate3d(0px, 0px, 0px); position: absolute; top: 0px; left: 0px; height: 978px; width: 1467px; max-width: none;"></div>`

But it never updates with the scroll event :-/

**Comment by hvsh** [comment]
can you post a link?

**Comment by JohnnyWalkerDesign** [comment]
It's fenced off at the moment. Maybe once it's live. I have a feeling it's got a simple solution... just can't think what, as I'm not getting any errors :-/

I'll see what I can do. Thanks!

**Comment by regenrek** [comment]
Hi, same problem here.

Here is an example link: http://www.macherjek.at/agentur

Regards

**Comment by JohnnyWalkerDesign** [comment]
I forgot to write back here and explain the problem I was having: Badly formed HTML. (Doh - schoolboy error!)

Try checking your code through the W3C Validator just to make sure you don't have a rogue DIV tag somewhere like I did!

**Comment by wstoettinger** [comment]
solved
