### ISSUE TITLE
Error when height website change !!!

### ISSUE THREAD

**Issue by KytoSai** [pixelcog/parallax.js#143]
Example:

<div class="test">
Click to height = 500px;
</div>

$('.test').click(function(event) {
  $(this).height(500);
});
# 

Before click "Test"
https://gyazo.com/76d2f60e8294e530b6dec7832e502501

After when click "Test"
https://gyazo.com/3a94eddc19976e3cbaa1edfc47c39698

Parrallax error with bottom div ! :(

Other, this plugin error when change height of tabs website
# 

Please fix this plugin, I love plugin ! 

Sorry because my english is bad ! >.<

**Comment by of6** [comment]
See the README notes, you'll have to fire a resize/scroll event when you change the dom

`jQuery(window).trigger('resize').trigger('scroll');`

**Comment by KytoSai** [comment]
Thank you , ^^ !!
Good luck to you !

**Comment by wstoettinger** [comment]
solved
