### ISSUE TITLE
Load time

### ISSUE THREAD

**Issue by etleyden** [pixelcog/parallax.js#144]
When the image is scrolled from view, it has to refresh. For larger .jpg images this is a problem. It takes too long. Also, the initial parallax effect lags once when it loads.

**Comment by TheTannerRyan** [comment]
The best solution to this is to reduce the image to the maximum required dimension, and also minify the image to maintain the best quality with the smallest file size. Use photoshop to alter dimensions and use Kraken to minify: https://kraken.io/web-interface

I've used this method on my website (http://www.hamiltonweather.ca) and it works rather well.

**Comment by wstoettinger** [comment]
is this still an issue? closing old issues for cleanup purposes. feel free to reopen if this issue is still relevant on the latest release.
