### ISSUE TITLE
can't solve the white space on top and bottom

### ISSUE THREAD

**Issue by rgalaxy** [pixelcog/parallax.js#145]
Hello, i am using parallax.js
i've searched all over the github and google how to fix this white space thing, i've tried almost all the method like, data-bleed or `
$(window).scroll(function(){
                    $(window).trigger('resize');
                });
` or

```
        `   jQuery(window).trigger('resize').trigger('scroll');`
```

also adding padding this and that, and make sure all background-size: cover;
but the white thing still remain there.. i hope somebody could really help me.. i've tried to solve this almost 5days and still can't fixed it :<

this is my current [site](www.odeo.co.id) it is not up-to-date yet, but i've tried all those thing in my local.. please help :sob:

**Comment by Legues** [comment]
Well i have the same problem.i removed the overflow:hidden form .parallax-mirror, and the white space disappear... but it´s not a good solution. are you using another plugin in the page you are having problems?

Sorry about my english!!

**Comment by rgalaxy** [comment]
wow ! it works @Legues thank you so much, and why is that not good solution? because i don't see any error with removing it..

ermn, i dont really use any other plugin, just using <script> to detect the scroll and do some animation.. if you can check on the bottom page of html [try this](www.odeo.co.id)

**Comment by jonaschen623** [comment]
I've tried other possible solutions, none works for me.

my solution is using bleed:

jQuery('.parallax-window').parallax({
  bleed:50
});

and change source code
    this.boxHeight       = this.$element.outerHeight() + this.bleed * 2;
    this.boxOffsetTop    = this.$element.offset().top - this.bleed;

to 

    this.boxHeight       = this.$element.outerHeight() + this.bleed;
    this.boxOffsetTop    = this.$element.offset().top - this.bleed * 2;

you may try bleed: 100 or 200 etc.

may fix your problem. :)

**Comment by artursopelnik** [comment]
@Legues Many thanks!!!

Bug:
http://codepen.io/artursopelnik/pen/vgMKbR

Bugfix:
`// https://github.com/pixelcog/parallax.js/issues/145
.parallax-mirror {
    overflow: visible !important;
}`

**Comment by riegeo** [comment]
Changing the bleed to 50 in the original file solved it for me:
```

t.extend(o.prototype, {
        speed: .2,
        bleed: 50,
        zIndex: -100,
        iosFix: !0,
....
```

**Comment by wstoettinger** [comment]
bug preview doesn't show any problems. seems to be solved!
