### ISSUE TITLE
fixed avec id=""

### ISSUE THREAD

**Issue by Poulpix83** [pixelcog/parallax.js#147]
bonjour, le background reste fixed si on ajoute un id

`<div id="index" class="parallax-container" data-parallax="scroll" data-position="top" data-bleed="0" data-image-src="./images/01.png">`
or
`<div class="parallax-container" data-parallax="scroll" data-position="top" data-bleed="0" data-image-src="./images/01.png">`

résolut en faite il aime pas id = index dsl ^^

**Comment by Veejay** [comment]
@Poulpix83 IN FRENCH: Essaye de communiquer en anglais dans la mesure du possible. Si tu écris en français, les anglophones ne comprennent pas forcément ce que tu veux dire.
SAME THING IN ENGLISH: Please try to communicate in English as much as possible. If you write your reports in French, it makes it much harder for maintainers to do triage work and understand your intent.

### For the maintainers

Poulpix82 actually ended finding the problem himself/herself, it was an issue with using id `index` apparently.
You can mark this as solved.

**Comment by wstoettinger** [comment]
thanks for the translation ;)
closing
