### ISSUE TITLE
parallax effect video

### ISSUE THREAD

**Issue by atul-bajpai** [pixelcog/parallax.js#148]
can we use html 5 video for parallax effect instead of image

**Comment by vitaly44** [comment]
Add, please.

This is not problem.

Just create template placeholder inner html at parralax-window

**Comment by willard** [comment]
Hi did you solve this issue? thanks

**Comment by evandiamond** [comment]
Can you explain this a little more? I'd like to have video as well.

**Comment by wstoettinger** [comment]
this should work using the html markup (see readme for details).

example:
```html
<div class="parallax-window">
  <div class="parallax-slider">
    <!-- place your html5 video here -->
  </div>
</div>
```
