### ISSUE TITLE
A Little Bug??

### ISSUE THREAD

**Issue by albertjt** [pixelcog/parallax.js#149]
Hello everyone,
I'm using Chrome to develop a simple parallax effect web. But when I resized the chrome browser (F12 or Inspect Element) to check if it is responsive or not, it is still working hehe..., until I refresh it in that state. Somehow the parallax effect stop. Is that suppose to happened? I tried it too on the main download page for this plugin, and it happened too, the parallax effect stops when I refreshed it in a resize chrome browser state. Though in a normal resized chrome browser (Did not use F12) that didn't happened. Should I be worried about this somehow?? Need explanation
Thank you :smiley:

**Comment by ametad** [comment]
It is suposed to work like that. Parallax is determining if the device is IOS or Android, if so the image is displayed without the parallax effect.

**Comment by nckblu** [comment]
That's strange, the plugin doesn't check screen size only user agent. Can you provide a plunkr?
