### ISSUE TITLE
Destroy Function or Fallback on small viewport

### ISSUE THREAD

**Issue by cspicuzza** [pixelcog/parallax.js#15]
Any chance to add a destroy function or defer to the fallback when the viewport is below a certain width?  

I love the fallback that exists for touch devices, it would be great to have that same fallback for when the viewport for no-touch devices goes below a specified width. 

This could be achieved manually if there was a destroy/reinit function

Thanks!

**Comment by mikegreiling** [comment]
closing pending further feedback.
