### ISSUE TITLE
Parallax doesn't updating after change height block

### ISSUE THREAD

**Issue by meverikxp** [pixelcog/parallax.js#150]
I have jQuery script which opened and closed block. After opening parallax doesn't show, I read need use resize trigger but it not help me. There is my code
`$('.openmore').click(function () {
                $('.lightdiv').slideToggle();
                if ($(this).html() == 'Show more') {
                    $(this).html('Close');
                } else {
                    $(this).html('Show more');
                }                
               $(window).trigger('resize');                
            });`
Thank. you.

**Comment by MikeMiller88** [comment]
Have the same issue....

**Comment by meverikxp** [comment]
I can answer On my question myself, I write  `$('.lightdiv').slideToggle(); ` slideToggle or any other similar function working with some delay so need run $(window).trigger('resize'); after this delay. Just need run with setTimeout
example is
`$('.openmore').click(function () { $('.lightdiv').slideToggle(**200**); if ($(this).html() == 'Show more') { $(this).html('Close'); } else { $(this).html('Show more'); } **setTimeout(function(){$(window).trigger('resize');},201)** });`

**Comment by ses** [comment]
i have the same bug.

`<div class="parallax-mirror" style="visibility: hidden; z-index: -100; position: fixed; top: 0px; left: 0px; overflow: hidden; transform: translate3d(0px, 0px, 0px); height: 300px; width: 2543px;"><img class="parallax-slider" src="http://www.domain.de/blaetter-fb.jpg" style="transform: translate3d(0px, 0px, 0px); position: absolute; left: 0px; height: 794px; width: 2543px; max-width: none;"></div>`

after change the height, dont update the parallax-mirror

**Comment by madranet** [comment]
Same here.  

I have a drop-down TOC div on a page. After triggering the drop-down, the background  image appears behind neighbouring text. Browser dev tools show the parallax window is still in the right place, but the background image has somehow become offset from it.

_Before activating drop-down:_
![2016-09-29_17-57-01](https://cloud.githubusercontent.com/assets/669658/18963975/e1c758e4-866e-11e6-912c-abda17527ad0.png)

_After activating dropdown:_
![2016-09-29_18-00-18](https://cloud.githubusercontent.com/assets/669658/18964011/045603ba-866f-11e6-8fef-81dfdae9ed6d.png)

Triggering a jQuery window.resize event [thanks @meverikxp!] fixes it, as does toggling or resizing the browser's dev tools panel.

**Comment by wstoettinger** [comment]
seems to be fixed with triggering resize. closing.
