### ISSUE TITLE
Dont work with jQuery 2.X -> No Image

### ISSUE THREAD

**Issue by JohannesRegner** [pixelcog/parallax.js#152]
The newest version don't work with jQuery 2.X
https://jsfiddle.net/mxk1ud65/1/ -> When you add jQuery 1.x it will work an show the image!

The most new websites, us the "newer" jQuery 2.X ...

**Comment by zcztig** [comment]
It works just fine, but in your fiddle the parallax.js script is not included. Add that and it will work with all versions of jQuery.

**Comment by JohannesRegner** [comment]
Under external resources, it is included!
Here with jQuery 2.2.4: https://jsfiddle.net/mxk1ud65/4/
The same fiddle with jQuery 1.11.0: https://jsfiddle.net/mxk1ud65/3/

Ok, i the error was, that i included first parallax and then jquery! 
I will check this on my website, but ticket can close!

**Comment by georgi-kovachev** [comment]
hi @JohannesRegner is this working with jQuery 2.2 with your test?
