### ISSUE TITLE
<img alt="..." [...] />

### ISSUE THREAD

**Issue by rbinder** [pixelcog/parallax.js#155]
Hi, all!

I would like to have an img-altText for parallax-images...

```
function Parallax(element, options) {
  ...
  if (!this.altText) {
    $.extend(this, {altText: 'parallax background-image'});
  }
  ...
  this.$slider[0].alt = this.altText;
}
```

Thanks,
Roman

**Comment by Maelstrome26** [comment]
+1

**Comment by Giovanni-Mattucci** [comment]
+1 This is an accessibility issue, easily fixed with adding an empty `alt=""` tag at least. Giving an option to set an alt task would be good.

**Comment by llahnoraa** [comment]
+1

siteimprove.com reported this as an accessibility issue. I am not sure how to add alt tag since this isn't image and is div?

`<div class="parallax-window" data-parallax="scroll" data-image-src="/Assets/sf/financial-aid/images/fa-background.jpg" title="">`

**Comment by Giovanni-Mattucci** [comment]
@llahnoraa you can apply it with javascript once the image has been rendered as a workaround.
Using jquery I did it like this: `$('.parallax-mirror img').attr('alt', '');`

Make sure this is after the plugin has loaded of course.

**Comment by llahnoraa** [comment]
Thank you for your reply. I tried this and didn't work. Your code stated `parallax-mirror` but should it be `parallax-window`?

**Comment by Giovanni-Mattucci** [comment]
Update the jquery selector to target the element you need in your implementation, you will need to inspect the page to see what is being created.

**Comment by llahnoraa** [comment]
The one I pasted above `<div class="parallax-window" data-parallax="scroll" data-image-src="/Assets/sf/financial-aid/images/fa-background.jpg" title="">` is the only one that I see on web inspector. 

Here is the link to the college website: [http://www.sfcollege.edu/fa/](http://www.sfcollege.edu/fa/) and [http://www.sfcollege.edu/planetarium/](http://www.sfcollege.edu/planetarium/)

Also, feel free to add these college pages to your showcase :)

**Comment by lt7** [comment]
+1

**Comment by santamaria7** [comment]
we do need the alt attribute for the img. It doesn't make sense to me why the developer has not considered this issue, and why he's not responding to these comments.

**Comment by wstoettinger** [comment]
this can easily be achieved with the html markup (as opposed to the data attributes markup, which is a simplified version). see the readme for instructions

**Comment by armandoaepp** [comment]
@wstoettinger en que parte del html markup?.

**Comment by wstoettinger** [comment]
@armandoaepp aqui te he copiado parte del readme. espero que puedes utilizarlo ;) (my Spanish is getting rusty :D )

HTML:
```html
<div class="parallax-window">
  <div class="parallax-slider">
    <img src="/path/to/image.jpg" alt="sometext" srcset="/path/to/image-400px.jpg 400w, /path/to/image-800px.jpg 800w, /path/to/image-1200px.jpg 1200w" sizes="100vw">
  </div>
</div>
```

CSS:
```css
.parallax-window {
	min-height: 400px;
	background: transparent;
}
```

javascript:
```javascript
$('.parallax-window').parallax({
    naturalWidth: 600,
    naturalHeight: 400
  });
```

**Comment by mdmpweb** [comment]
Hola. Lo has podido solucionar?. Por temas de accesibilidad sería necesario que aparezca alt en imagen y no lo consigo.
Gracias

**Comment by adarshsriv** [comment]
I tried Applying the changes mentioned https://github.com/pixelcog/parallax.js/issues/155#issuecomment-339386078

The parallax is not working properly the images are not moving upward/downwards.

Any help?
