### ISSUE TITLE
Color Overlay of the image 

### ISSUE THREAD

**Issue by weilinzung** [pixelcog/parallax.js#156]
I tried to put colour overlay of the image, on Desktop I am fine by just put the colour on the div. But on mobile device that the colour is not showing. Any correct way I should do?
here is my code and markup. thanks
`<section class="test"  data-parallax="scroll" data-image-src="<?php echo $image_parallax; ?>"> <section>
`

```
.test {
overflow: hidden;
 min-height: 100%;
 background-color: rgba(189,121,2,.7);
}
```

**Comment by ner00** [comment]
Were you able to solve this at the time you closed this issue?
