### ISSUE TITLE
Firefox: Black Flash on Page Load

### ISSUE THREAD

**Issue by wyzrd** [pixelcog/parallax.js#157]
Wherever the image is loaded, it creates a flash of black on page load or refresh. 

This happens in Firefox but not in Chrome. It also happens on the demo site.

Is there a way to remove it or make it white instead?

**Comment by wstoettinger** [comment]
can't confirm that in the latest version. 

pd: i'm closing this now because the issue is already very old. in case you still have the problem. feel free to reopen.
