### ISSUE TITLE
data-position-y not working 

### ISSUE THREAD

**Issue by skilleddesigner** [pixelcog/parallax.js#158]
Hi
i am sure i am asking something simple but sorry i am not a coder.  My Question is 
I have tried  **data-position-x="'** which works perfectly fine. but when i tried **data-position-y=""** it doesnt work. Any idea how to make it work?

thank you

**Comment by swthate** [comment]
I'm experiencing the same thing :(

**Comment by jcfrancisIII** [comment]
I am also experiencing this problem with position-y

**Comment by buniden** [comment]
I'm also experiencing this.

**Comment by phifa** [comment]
can confirm. it does not work. is there a fix available?

**Comment by phifa** [comment]
I had a look at the code, but I have no idea. Maybe @mikegreiling can have a look?

**Comment by glennnall** [comment]
same problem - the positionX works fine, but I can't get Y to work even tinkering with the js code.

I have a .sticky-header, and I was thinking that was causing the Y value to fail. no success yet.

apparently the author isn't interested.

**Comment by guytzhak** [comment]
I'm experiencing the same thing too. I had a Steaky header and think this should be the problem....

**Comment by guytzhak** [comment]
I fix it by adding the calculated height of the sticky header to my img in mirror class:

```
img.parallax-slider {
    margin-top: 215px;
}
```
something like this

you could do it in JS to calculate the height's values.

**Comment by meshucs** [comment]
We'll take a stab at it and what looks to be some calculation issues with the base variables. 

Great library, btw.

**Comment by wstoettinger** [comment]
please read @mikegreiling comment in #24 or mine in #191. might be the reason
