### ISSUE TITLE
Not working smoothly on Firefox, IE and Safari

### ISSUE THREAD

**Issue by panatapattu** [pixelcog/parallax.js#159]
Hi,
Parallax images working perfect in the Chrome. But it is not in Firefox, IE and Safari. But if I remove the the content it is working smoothly in all the mentioned browsers.

Is there anything else do I need to do to make this smooth to all the browsers or where I am wrong..?

This is a setup code snippet.

`<section class="my-class parallax-window" data-parallax="scroll" data-image-src="img/excursion.png"></section>`

I also tried this with the data-natural-width and data-natural-height

**Comment by squalltua** [comment]
I found problem like this. But in Chrome. In Firefox and Edge is working smoothly.

**Comment by caseydev** [comment]
yes in firefox little bit stuck while scrolling parallax section

**Comment by mciszczon** [comment]
Make sure you optimize your images. I also found plugin to be really slow on my Chrome. But I was developing a site so I used images as I got them from the web. And these were 4mb giants with huge sizes like 4000x3000. After scaling them down to FHD and lowering quality from 100 to 90 everything works fine.

**Comment by wstoettinger** [comment]
should be fixed with the performance improvements in the latest release
