### ISSUE TITLE
Position

### ISSUE THREAD

**Issue by fabiovaz** [pixelcog/parallax.js#16]
First your script is wonderful.

 But I'm having a problem, I have a div with 500px in height at the top of the page when I use the bottom position option, still remains much below the image area, I can not adjust to it to rise more.

 Thank you.

**Comment by Landish** [comment]
Have a same issue, any solutions?

**Comment by mikegreiling** [comment]
This is an enhancement I would like to make for the library at some point...  the reason this occurs is that the parallax position does not take into account where the element is within the document.

If the image were anywhere else in the document, the parallax "slider" will need slack both above and below the image to accommodate the effect when scrolling up or down, but at the top it doesn't need to accommodate the image scrolling up, so it should calculate things differently...

Short answer is there is no quick way to fix this at the moment and I do not currently have the time to make the changes to the library, but if anyone else is willing to submit a pull request I would be happy to update it.

For now, you may be able to alleviate the problem a tad by modifying the image height and padding the bottom.  I realize this is not ideal.

**Comment by mikegreiling** [comment]
Just went in and implemented a quick fix for this.  v1.3 should no longer have this issue.
