### ISSUE TITLE
parallax cover image

### ISSUE THREAD

**Issue by Muphet** [pixelcog/parallax.js#160]
Hi. is it possible in any way to set first top parallax window to be cover (fullscreen) and then position object withing that window? I tried using cover attribute but script seem to be overwriting min-height anyway.
Guide says we can initialize slider inside. I tried to make this "scroll down" thing sticky to window but since first image is not fullscreen, position:fixed won't work. Again, tried to inherit or set position to relative but percentage values doesn't work after.

So in the end: how to enable cover sized picture and/or set object to be fixed to parallax-window so resizing works?

**Comment by wstoettinger** [comment]
for a fixed overlay please refer to #209. make sure, that the overlay is transparent and has a defined height. I guess it is possible to make that overlay sticky when scrolling down.
