### ISSUE TITLE
Setting data-bleed to non-zero causes previous non-parallax div height to shrink

### ISSUE THREAD

**Issue by paultechguy** [pixelcog/parallax.js#164]
If I have a normal div with a set height of x, followed by a parallax div with a data-bleed of y, the normal div will be x-30 in height.

**Comment by wstoettinger** [comment]
can you provide a link with an example? would be great to be able to solve that issue!

**Comment by paultechguy** [comment]
I went back and looked at this, having worked around the issue back when I made the post.  I was unable to  reproduce the issue, trying to make changes to reproduce it.  Maybe that is good news and possibly it was Chrome back then.

**Comment by wstoettinger** [comment]
okay, good to hear! i'll consider this solved then. 
feel free to check out the brand new v2.0.0-alpha here:
https://github.com/pixelcog/parallax.js/tree/v2.0.0-alpha

i'd love to get some feedback and support with testing!
