### ISSUE TITLE
Background can be set via css instead of inline data-image-src

### ISSUE THREAD

**Issue by caseydev** [pixelcog/parallax.js#165]
Hi, can i add background image via css instead of data-image-src? Please help me to do that

**Comment by nckblu** [comment]
In theory you could make use of the 'imageSrc' option when initialising the plugin. Like so:

```
$('.your-element').parallax({
 imgSrc: $('.your-element').css('background-image');
});

// Then remove the background from the element so the mirror will show through
$('.your-element').css('background-image', 'none');

```

This would work as long as you include a way to strip the 'url()' part of the css property.

**Comment by caseydev** [comment]
Ok thanks for the quick response. Actually i meant can't we add from external css files. Like i have 3-4 parallax section in one page all have different selector and can be use bg image by calling from external css files.
