### ISSUE TITLE
parallax won't show up

### ISSUE THREAD

**Issue by abdelhak1** [pixelcog/parallax.js#171]
parallax won't show up unless i put some text in it or some `<br>`s

**Comment by jbabrams2** [comment]
Same. I can't get it to show up at all...even with text inside...

**Comment by jbabrams2** [comment]
ended up being that I was using v. 3.1.0 of jquery. Switched to v 1.11.0 and it works fine.

**Comment by egurelli** [comment]
If you are using jQuery above version 3+, you can use also migrate plugin.

https://code.jquery.com/jquery-migrate-3.0.0.min.js

https://github.com/jquery/jquery-migrate/

**Comment by hellsing71** [comment]
Try to set <body> background to transparent and <html> to anything. It's crazy but it seems Parallax appears behind <body>.

**Comment by Aznbai** [comment]
@egurelli 
thank you for your comment on the migration issue.

[](https://code.jquery.com/jquery-migrate-3.0.0.min.js
)
it does the job! maybe the whole thing should be rewriten to function with last jquery...

**Comment by wstoettinger** [comment]
@abdelhak1 this is explained in the readme. a min-height of the .parallax-window has to be set.
@jbabrams2 @egurelli @Aznbai jquery 3 is supported as of #201
