### ISSUE TITLE
Parallax image does not show up on mobile

### ISSUE THREAD

**Issue by uzomao** [pixelcog/parallax.js#172]
The plugin works perfectly on desktop and even on the in-built Chrome mobile inspector. However on an actual mobile device the image fails to show up. I can't seem to detect the source of this issue and any help doing so would be appreciated.

My test site can be found at http://46.101.33.127/#/howItWorks

Thank you.

**Comment by tarawhiteley** [comment]
Make sure you do not have spaces in your file names. That was my problem.

**Comment by wstoettinger** [comment]
are you using the data-attribute markup or the html markup? 

is this still an issue? closing old issues for cleanup purposes. feel free to reopen if this issue is still relevant on the latest release.
