### ISSUE TITLE
Absolute positioned elements tear on scroll in Firefox and Edge

### ISSUE THREAD

**Issue by LoonMaster** [pixelcog/parallax.js#176]
Is there any way to implement browser specific exclusions?

I have an absolute positioned element masking a section of the parallax window and when the user scrolls up when viewing in either Firefox or Edge it causes very noticeable tearing on that element.

**Comment by wstoettinger** [comment]
this seems to be a performance issue which might be fixed in the current release.

**Comment by wstoettinger** [comment]
is this still an issue? closing old issues for cleanup purposes. feel free to reopen if this issue is still relevant on the latest release.

**Comment by avoliva** [comment]
If I absolutely position an image to the bottom of the parallax element, it "tears" when scrolling really fast. I'm guessing it's the delay from the absolute element trying to position itself to the bottom every time the parallax element moves.

**Comment by avoliva** [comment]
I'm still getting the tearing effect on the top too unless I had a high bleed.

**Comment by wstoettinger** [comment]
could you provide a link to an example?
