### ISSUE TITLE
Issue with images using bxSlider

### ISSUE THREAD

**Issue by Fortyfive** [pixelcog/parallax.js#177]
Hi, when using parallax images in bxSlider the first slide's image appears and the slide text continues to change from slide to slide, but the parallax background images stay as slide 1 and don't change. Could you please help? Thanks!

**Comment by shelune** [comment]
This is probably because the image stays as it's positioned 'fixed'. The 'background' is actually a div slabbed near the top of the <body> tag so you need another way to deal with carousel.

If you slide image is an actual image, try changing the z-index.

**Comment by Fortyfive** [comment]
Thanks

**Comment by wstoettinger** [comment]
it is possible to implement a slider/carousel within the parallax element but not the other way around. see #88 for an example
