### ISSUE TITLE
Scrolling make "Ghost effects"

### ISSUE THREAD

**Issue by RSickenberg** [pixelcog/parallax.js#181]
https://rsickenberg.github.io/portfolio/

When you scroll down the text moves like an exited guy on Redbull 😂

No seriously, is it an issue ?

**Comment by matrixfox** [comment]
When I scroll, the images flicker upward 2 pixels, then reset to the original position. This happens on Safari Version 10.0.2 (12602.3.12.0.1) with a late 2015 5k iMac. What browser are you viewing this on?

**Comment by RSickenberg** [comment]
Chrome, Firefox and others

**Comment by wstoettinger** [comment]
is this still an issue? closing old issues for cleanup purposes. feel free to reopen if this issue is still relevant on the latest release.

**Comment by RSickenberg** [comment]
Yes it's still an issue
