### ISSUE TITLE
data-image-src issue on Chrome Browsers

### ISSUE THREAD

**Issue by wilsonlego** [pixelcog/parallax.js#182]
When I use "data-image-src" on the latest Chrome browser, no image is loaded to the page.
Works fine for Firefox and IE though.

Anyone got a hack around this?

**Comment by BastiHo** [comment]
I had the same problem. Quick workaround:


    $('[data-parallax="scroll"]').each(function() {
        var $this = $(this);
        $this.parallax({imageSrc: $this.data('image-src') });
    });

**Comment by AnalogMemory** [comment]
This is happening for me as well on Safari and Firefox. I had to force it to initialize with

`$('.parallax-item').parallax();`

After that it read my data attributes just fine. Pretty sure it was working fine with just the data attributes a few months ago.

**Comment by glenndavey83** [comment]
Still fucking up on Chrome for me. It actually worked, briefly, and I don't know how to get it back. It now just puts the background-image on the parallax-window element, rather than creating the parallax-mirror element like it should.

Works in Firefox, etc, but not Chrome. So close...

**Comment by alto-Bjoern** [comment]
Had the same issue of 'suddenly not working anymore'. I traced the problem back to switching from jQuery 2.x to jQuery 3.x - with 3.x I suddenly need the forced initialization.

**Comment by evandiamond** [comment]
Has this been merged in? I am having the problem as well :(

**Comment by of6** [comment]
@evandiamond Has what been merged in? This is a issue thread not a pull request. You can fix the issue by calling parallax.js manually. 

`$('.parallax-item').parallax();`

**Comment by samparmenter** [comment]
Thats not a fix, thats a workaround. Its cleaner to use data attributes to load the parallax and the fact it isn't working is an issue. We know we can get around this but hes drawing attention to an issue.

**Comment by verena-isolde** [comment]
I had this same problem, and the .parallax(); workaround worked for me.

**Comment by wstoettinger** [comment]
fixed with #201
