### ISSUE TITLE
Different responsive image sizes

### ISSUE THREAD

**Issue by philippdanne** [pixelcog/parallax.js#186]
Is there any way to implement different resolutions for the images on mobile devices like it is with _srcset_ in the img-tag?

**Comment by artursopelnik** [comment]
I think only manually with: `$('.parallax-window').parallax({imageSrc: '/path/to/image.jpg'});`

Use Debounced Resize() jQuery Plugin and check for window.matchMedia("(min-width: 400px)").matches.

**Comment by wstoettinger** [comment]
@philippdanne you can use the srcset when using the html markup. please check the readme for more details.
https://github.com/pixelcog/parallax.js#using-inner-html-for-complex-content

**Comment by nattyluke** [comment]
Would be a great feature to have the srcset possibility with data attributes, something like
	data-image-srcset
Would love to have this
