### ISSUE TITLE
data-position-x="right" on Mobile / Specified Width Only

### ISSUE THREAD

**Issue by abaney** [pixelcog/parallax.js#189]
The parallax image works perfectly. However, when I scale my browser window down to mobile size ("tablet vertical" and smaller), the right portion of the image is cropped off. It's good to center the background image vertically and horizontally for larger screens, however, for mobile applications, the image is cut off on the right, and it just looks weird.

I added `data-position-x="right"` to the parallax container, and the image looks much better (not perfect, but acceptable) on mobile. On larger screens, however, the background image is too far to the left.

Is there a way to say in the code "if the window width is 980px or less, use `data-position-x="right"`"?

Thanks for this amazing jQuery plugin!

**Comment by abaney** [comment]
Ideally, it would be best / more flexible to add this as JS rather than inline with the parallax container.

**Comment by wstoettinger** [comment]
do I understand it correctly, that you want to have different `data-position-x` attributes for desktop and mobile? please be aware, that this library (like many many others) currently doesn't support mobile, it just shows static images (hence the iOS and Android fixes).

**Comment by wstoettinger** [comment]
please refer to #184 for mobile support
