### ISSUE TITLE
My image is in the CSS file

### ISSUE THREAD

**Issue by TheCodingGuy** [pixelcog/parallax.js#19]
Hello there! 

I must your script looks amazing! But i have a problem....
The image i'm trying to enable parallax.js on is in my CSS file... and i have several other images in the same file i'd to have a parallax effect on. 
The IDs for the different classes are wrapped up in div tags in my HTML, this is the code for the header ID etc:

```
.header{
	background: url(../images/banner.jpg) no-repeat center top;
	-webkit-background-size: cover;
	-moz-background-size: cover;
	-o-background-size: cover;
	background-size: cover;
	position: relative;
	padding-top:19em;
	min-height:870px;
	text-align: center;
}
```
I have tried to use JS method, and as i expected it did not work....

Should i try to put the image source in the "div="header"" nest and hope for the best or is there any other solution?

Thanks in advance!

**Comment by scottblinch** [comment]
This is a fairly old issue but we ended up using javascript to grab the image source from the CSS.

```javascript
var bg_src = $bg.css('background-image'); // $bg is the jQuery object of the element we're parallaxifying
bg_src = bg_src.replace('url(','').replace(')',''); // background-image is wrapped with url('') so remove it
$bg.css({'background': 'transparent'}); // make the bg transparent for the parallax to work
$($bg).parallax({
	imageSrc: bg_src
});
```

**Comment by mikegreiling** [comment]
Thanks for the feedback @scottblinch.

@TheCodingGuy sorry for my lack of response.  I think this issue slipped under the radar after the holiday season and I never got back to it.  Did you manage to resolve this issue?  I don't see an example of the parallax usage on the github repo you referenced.

Closing for now, pending further feedback.

**Comment by mjrev** [comment]
@scottblinch 
this won't work on firefox, because on second line there will be string in quotes, so there will be `%22` in url
here's working variant:
```javascript
bg_src = bg_src.replace('url(', '').replace(')', '').replace( /['"]/g, "" );
```
