### ISSUE TITLE
Only background-position added, no mirror

### ISSUE THREAD

**Issue by matzeso** [pixelcog/parallax.js#190]
Hey there,

I am having issues with the parallax.js, I am now trying to add this for 2 hours and nothing seems to work. The image is not shown, there is almost no inline-css in the window and no mirror in the code.

<img width="726" alt="bildschirmfoto 2017-03-25 um 13 02 59" src="https://cloud.githubusercontent.com/assets/4353397/24322004/99eba2a0-115b-11e7-95fc-593998fd6693.png">

I am using Wordpress with the standard jQuery Version from WP 4.7, including jQuery migrate. I tried with explicit JS call `$('.parallax-window').parallax();` and also with

```
$('[data-parallax="scroll"]').each(function() {
        var $this = $(this);
        $this.parallax({imageSrc: $this.data('image-src') });
    });

```

as suggested in other issues. But nothing helped. The area that should contain the parallax image is blank. I also de-registered the standard jQuery and used the newest Version 3.2 - nothing changed, the result is the same. There is no parallax mirror div and the window does not have any other inline-style than the one from the picture. How is this possible?

Any idea how to fix this? The same result on Chrome and Safari.

**Comment by wstoettinger** [comment]
@matzeso if there is no parallax-mirror element, then the library wasn't called properly. This could be due to an error before or during initialization of parallax.js. please check your console for errors and post them if necessary. also the latest version v1.5.0 supports jQuery 3.x
