### ISSUE TITLE
Parallax not working in Mobile devices

### ISSUE THREAD

**Issue by upalr** [pixelcog/parallax.js#193]
Does this Parallax work on mobile phones? I can't seem to get the script to work on my Android. Any help appreciated. Works on Desktop.

**Comment by IsaacAbrahamson** [comment]
Try reading the README options section, it should be very obvious that it is disabled on mobile devices.

**Comment by wstoettinger** [comment]
please refer to #184

**Comment by mattlindsay** [comment]
Not working with gyroscope or motion detection on mobile. Is there a fix coming anytime?

**Comment by wstoettinger** [comment]
@mattlindsay this parallax effect is only intended for scrolling and not for motion detection in mobile devices. so this is not a bug which needs to be fixed. I presume this feature will also not be implemented in the near future.
