### ISSUE TITLE
changed aspect ratio

### ISSUE THREAD

**Issue by jjonell** [pixelcog/parallax.js#199]
It behaves weird when using picture element where the individual images have different aspect ratios. To solve, I had to first reset the naturalwidth + naturalheight on window resize, and then add the following code after line 171: 
this.aspectRatio = this.naturalWidth / this.naturalHeight;

**Comment by wstoettinger** [comment]
could you provide a live example (jsfiddle or similar)? or at least your html markup?

**Comment by wstoettinger** [comment]
closed due to inactivity
