### ISSUE TITLE
parallax-mirror visibility doesn't change when next slide come

### ISSUE THREAD

**Issue by MortezaAghili** [pixelcog/parallax.js#202]
I have a bootstrap slider(carousel) with 2 slider items. The parallax plugin generate 2 parallax-mirror with some css attributes like this: 
`visibility: hidden; z-index: -100; position: fixed; top: 100px; left: 0px; overflow: hidden; transform: translate3d(0px, 0px, 0px); height: 0px; width: 0px;`

But when the next slide come, the visibility attribute still hidden and do not change at all unless the browser's window height change manually! 

any idea?
Thanks.

**Comment by wstoettinger** [comment]
I successfully implemented a carousel once with owl but put the carousel within the parallax, not the other way around. it worked like a charm. see #88
