### ISSUE TITLE
Trigger Update function

### ISSUE THREAD

**Issue by iamharidasan** [pixelcog/parallax.js#204]
Need a update function because positions needs to be updated after height of previous element has been changed.

**Comment by blindMoe** [comment]
+1 for this

**Comment by blindMoe** [comment]
This answer is in this issue:

https://github.com/pixelcog/parallax.js/issues/200

 $(window).on("debouncedresize", function(event) {
    setTimeout(function() {
      $(window).trigger('resize.px.parallax');
    }, 375);
