### ISSUE TITLE
How to use this plugin with background-image

### ISSUE THREAD

**Issue by D-Marc1** [pixelcog/parallax.js#205]
Maybe I'm missing something here, but it seems like there is no way to use this plugin with the CSS `background-image` property. This would be great for using with `background-size: cover`.

**Comment by wstoettinger** [comment]
should be working when using the html version. make sure to set a minimum height for the parallax-window and the element with the background. 
```html
<div class="parallax-window">
  <div class="parallax-slider">
    <div class="with-background-image">Div with background image and minimum height</div>
  </div>
</div>
```

```javascript
$('.parallax-window').parallax();
```

**Comment by dspacejs** [comment]
@wstoettinger where can I find the styles for those classes in the mark-up?

**Comment by wstoettinger** [comment]
@dspacejs natively this library doesn't use styles. It just uses the class names to identify the elements.

**Comment by dspacejs** [comment]
@wstoettinger ah right. Thanks!
