### ISSUE TITLE
Not Working in WordPress/Genesis Theme

### ISSUE THREAD

**Issue by Nadareh** [pixelcog/parallax.js#207]
Hi everyone, I'm not sure what's wrong but I can't seem to get it work on the site I'm building. :'(

I have this: `<div class="ebs-cta parallax-window" data-parallax="scroll" data-position="top" data-image-src="/wp-content/uploads/2017/08/ebs-cta-bg-parallax.jpg" data-natural-width="1400" data-natural-height="726">{..my other elements inside..}</div>`

I don't know what's wrong. Any help? Thanks

**Comment by Nadareh** [comment]
It shows a blank image only. http://prntscr.com/gbrpsy

http://prntscr.com/gbrq0w

**Comment by wstoettinger** [comment]
data-attributes unfortunately don't work properly in the current version (see #183). this is a known bug and will be fixed for the next release. try calling:
```javascript
$('.parallax-window').parallax();
```

**Comment by wstoettinger** [comment]
bug fixed with jQuery 3 support in #201
