### ISSUE TITLE
Add a possibility to disable parallax for all devices the way it is done for iOS

### ISSUE THREAD

**Issue by Simpleqode** [pixelcog/parallax.js#208]
I am looking for a way to give users a possibility to disable the parallax effect for any type of devices the way it is done for iOS via JS. I could have done it by changing the speed value to 1, but this works poor on browsers like Edge, so it'd be best to set the image as a background image for the [data-parallax] container like it is done for iOS and Android fix. Thanks.

**Comment by wstoettinger** [comment]
why not just prevent the library being initialized when the user doesn't want the parallax effect? you could also call `$('.parallax-window').parallax('destroy');` in case it has been initialized already

**Comment by anephew** [comment]
@wstoettinger This breaks the block with the picture, after that just a white space. It is necessary that it be the same as on iOS and Android - the picture was in place, as background, but without parallax
