### ISSUE TITLE
fixed navigation jumping sections

### ISSUE THREAD

**Issue by treyfenton** [pixelcog/parallax.js#21]
Sup dude!

Love the script, and glad you've sourced it for the masses... I had one issue, however... I created a fixed nav at the top, obviously with the hopes it would stay fixed while scrolling and the parallax effect would be all the same for the backgrounds below. But when I scroll down the page, my nav "jumps" to the top of the next parallax background when it comes into page view. After which it scrolls up with the page to the top, where it sits fixed for a moment as I had planned, only to "jump" again when the next parallax section comes.

Does that make sense?

I noticed it works fine in IE. Is this just a Chrome bug then?

Do you know the fix?

ANY AND ALL HELP TO RESOLVE THIS IS GREATLY APPRECIATED!!!!!!!!!!!

Thanks!

**Comment by mikegreiling** [comment]
If you have a staged webpage online somewhere I can take a look at it, I would be happy to check it out.

**Comment by treyfenton** [comment]
Hey what's up Mike,

I actually figured it out a while back. Probably should have posted in
forums.
Nonetheless, I appreciate the response, and absolutely LOVE the script!

Best,

Trey Fenton

**Comment by mikegreiling** [comment]
Glad to hear it.
