### ISSUE TITLE
Scrolling make "Ghost effects"

### ISSUE THREAD

**Issue by RSickenberg** [pixelcog/parallax.js#217]
I reopen this issue : https://github.com/pixelcog/parallax.js/issues/181

It's still there on the latest version : 20 October 2017

**Comment by wstoettinger** [comment]
i could only reproduce it on IE11 and IE12 when opening the page multiple times. still seems to be a performance issue.

try adding a div around your center section (between the two parallax images) and remove the bleed of the parallax. 
might help

for the record, this is the page we are talking about: https://rsickenberg.github.io/portfolio/

**Comment by wstoettinger** [comment]
any news here?

**Comment by RSickenberg** [comment]
Will try, thx :)

**Comment by RSickenberg** [comment]
The div around seems okay, but not the bleed remove :)

**Comment by RSickenberg** [comment]
Sure, thanks :)
