### ISSUE TITLE
Parallax won't show except when resizing the window or bringing up development tools

### ISSUE THREAD

**Issue by SwalFord69** [pixelcog/parallax.js#219]
Parallax doesn't show until i resize the window or 'Inspect Element'.  Not sure what is causing this but it looks like the parallax might be showing too far up the page so it might be positioning incorrectly.  I have tried using the attributes and calling it manually using jQuery.

This is happening on both Safari and Chrome.

Any help would be greatly appreciated as I love the parallax effect when it's working!

Thanks

Richard

**Comment by wstoettinger** [comment]
did you also trigger a refresh after calling it manually?

**Comment by taskall** [comment]
I have the same problem but this "effect" does not happen in Firefox neither Opera, but only in chrome (i do not use Safari). 
Is there any way to fix it?

**Comment by SwalFord69** [comment]
Thanks for the replies.  I ended up fixing this by upgrading to the 2.0 beta.

I didn't trigger a refresh although I tried both calling it manually and with the attributes to the same effect.  I'd be interested to hear what the issue was.  I was getting it in both Chrome and Safari if that helps you taskall?

Thanks

Richard

**Comment by taskall** [comment]
I just tried the new version but still have the same problem with chrome (firefox and opera appears correct).
I have include:
  min-height: 50vh;
  background: transparent;

in my class. Is there any other action that i need to do? since i am new user of css and html and maybe i miss something.

Thank you

**Comment by taskall** [comment]
Dear SwalFord69,

I have upload my site to a server i order to share it. The problem still exists. Moreover i have different behavior in browsers (chrome and opera parallax image works fine but not with video background - firefox video parallax works fine but not the images) please check it out and give some recommendations. http://www.iconic3d.gr/index.php

Thank you in advance

**Comment by TheConceptBoy** [comment]
Unfortunately still an issue with 2.0 in Opera. I have to hold ctrl and resize the window to see the image.
