### ISSUE TITLE
Problem with fixed menu (Chrome, Bootstrap)

### ISSUE THREAD

**Issue by JaredNinja** [pixelcog/parallax.js#22]
Hello,

Parallax.js seems to have a bug. I build my website in Firefox where everything works great. Then I checked other browsers (Internet Explorer, Safari & Chrome). In Chrome, the fixed (bootstrap) main-menu was no longer fixed. It started moving upwards when scrolling (only in Chrome).

After reading another post, I removed 'transform: translate3d(0px, 0px, 0px)' from the script. It somewhat improved it (menu stays at the top at first), but it is still very much buggy. For instance, there will be 2 menu-bars when you scroll back to the top from the bottom.

Edit: My fault. Transform is used twice in the script. Initially I only deleted the first one. After deleting the second one, the behavior in Chrome is now identical to other browsers.

**Comment by jeremy-breidenbach** [comment]
I encountered the same bug, and commenting out both lines of 'transform: translate3d(0px, 0px, 0px)' from the script also fixed it for me in Chrome.

**Comment by treyfenton** [comment]
Omg... THANK YOU SO MUCH.

**Comment by mikegreiling** [comment]
This issue appears to be resolved.  I am leaving the `translate3d` transform within the source for now as in most cases it appears to help performance, but I will reference this solution as an option when anyone runs into rendering conflicts with this method.
