### ISSUE TITLE
Hide parallax window from print

### ISSUE THREAD

**Issue by epapada** [pixelcog/parallax.js#222]
Hi! I cannot find a way to successfully remove a parallax window when printing. Tried with css and @media print but no luck. Is there a way?

**Comment by epapada** [comment]
It is possible by hiding both parallax-mirror and the parallax-class. So I guess thats ok. Maybe a js option for disabling printing would be useful.

Cheers.

**Comment by wstoettinger** [comment]
that's usually done via css, not js. as you explained correctly, the solution is to hide the parallax-mirror and the parallax-window (or similar class you are using).
Thanks for posting the solution!
