### ISSUE TITLE
Resize trigger not functioning correct.

### ISSUE THREAD

**Issue by Nick-lab** [pixelcog/parallax.js#226]
hey :) just a small issue nothing major. I have another script to watch the "body-container" for a resize  and then sends the JQuery(window).trigger('resize').trigger('scroll'); however it only works when the parallax is not in view. any ideas what might be the cause of this?

**Comment by wstoettinger** [comment]
I am guessing you are talking about v2? No, not yet. I'll have a look at it!

**Comment by Nick-lab** [comment]
okay it's nothing major so don't waist any sleep on it, just something i would like to clean up.

**Comment by wstoettinger** [comment]
you could also try to use `$('.your-parallax-selector').parallax('refresh');` in v2 to request a refresh manually. Let me know if that works!

**Comment by Nick-lab** [comment]
no that didn't work unfortunately

**Comment by wstoettinger** [comment]
could you provide a link for testing?

**Comment by Nick-lab** [comment]
yea here is the link the script is at the top http://smi.swdlab.com/

**Comment by wstoettinger** [comment]
first of all: with `$('#body-container').parallax('refresh');` you are creating a new parallax element. you should use `$('.parallax-window').parallax('refresh');`

**Comment by wstoettinger** [comment]
any news?

**Comment by andrewvincent** [comment]
Question related to this topic. I am designing a site and using this parallax effect. I also have a menu toggle and I am not able to figure out how to get the parallax window to resize when the menu toggles.

I tried:
 $("#menu-toggle").click(function(){
            	$('.parallax-mirror').parallax('refresh');
        });

but it doesn't work as expected, it just keeps creating new parallax-mirror div's. I then tried to change to .parallax-window as suggested above, but that didn't do anything at all.

Any suggestions?

**Comment by phuquoc164** [comment]
Dans my page https://bigmat.rnd.fr/44-materiaux/blain/, resize trigger is not functioning correct. I tried to use $('.parallax-mirror').parallax('refresh'); but it made me to go crazy.

Any suggestions ?

**Comment by wstoettinger** [comment]
@phuquoc164 this page is not accessible without authorization. 
i'm closing this issue now since the OP's question seems to be answered.
if your question is still relevant, please turn to stackoverflow for help or create a new issue in case you found a bug.

**Comment by chrisames** [comment]
Did this ever get resolved? I've tried everything :(
