### ISSUE TITLE
JS Errors on mobile

### ISSUE THREAD

**Issue by n1smo** [pixelcog/parallax.js#228]
Hi,

i cant get the 2.0 alpha working on mobile. 
There is no background set on the parallax container and im getting the following error.

[Error] TypeError: undefined is not an object (evaluating 't.children')
on line 870

Im using the latest version and trigger the parallax effect with data attributes.
No Problems on desktop.

Any ideas?

Kind Regards
N

**Comment by wstoettinger** [comment]
thanks for this feedback! 

it should be fixed with the latest commit! For mobile there is still a fixed background image, however i'm planning to implement parallax for mobile as well (needs special implementation due to less browser support).
