### ISSUE TITLE
Using parallax.js and bulma troubles

### ISSUE THREAD

**Issue by maksakoviliya** [pixelcog/parallax.js#229]
Using bulma.io framework parallax doesn't work.

**Comment by wstoettinger** [comment]
without some more information, its impossible to help you with that! 

please provide sample code, more detailed explanation and a link to your implementation!

**Comment by sircEUNHO** [comment]
This is still occurring, the default z-index is not working on Bulma, when i changed the z-index to 0, the parallax shows
