### ISSUE TITLE
Using Alt and Title in the parallax image

### ISSUE THREAD

**Issue by Steelhammer100** [pixelcog/parallax.js#230]
Currently there is no possibility for adding an alt- or title-Attribute to .parallax-slider. Is it possible to copy it from the source image? At the moment this is a SEO and Accessibility problem.

**Comment by wstoettinger** [comment]
if you use the complex html syntax (as opposed to data-attributes), the element is taken as-is and alt attributes are conserved. 

Please check the following section in the readme:
https://github.com/pixelcog/parallax.js#using-inner-html-for-complex-content
