### ISSUE TITLE
Video Tutorial

### ISSUE THREAD

**Issue by joshuaSmith2021** [pixelcog/parallax.js#232]
I have been interested in parallax.js ever since I first saw it. However, I have not been successful in using it even after reading the instructions in the README, looking at the example online, and more.

I have looked for a video tutorial, but I haven't found one. I would appreciate one being made so I (and others like me struggling) can use the plugin easily.

**Comment by decombs12** [comment]
This video follows this developer's code and should help.

https://youtu.be/d34GsFz-HkY

**Comment by joshuaSmith2021** [comment]
Thanks for the video! I will definitely be able to use this video for good stuff.
