### ISSUE TITLE
Mirror not created in IE9

### ISSUE THREAD

**Issue by CapicheDesign** [pixelcog/parallax.js#238]
Hi there, I'm experiencing this issue in IE9 only. No `.parallax-mirror` elements are being created in the DOM on page load. Everything functions as expected in IE10 & 11 and other major browsers, and I see no errors in the console. 

I have tried triggering via javascript rather than data-attributes, and adding the explicit triggers: (e.g. `jQuery(window).trigger('resize').trigger('scroll');`) - but nothing seems to be working. 

Any ideas what I might be missing here? Thanks in advance.

**Comment by wstoettinger** [comment]
Hey there! Have you tried V2 alpha as well? 

Unfortunately I don't have any idea why this might be nor do I think it's even necessity to evaluate this further. The global browser usage of IE9 is around 0.13% and we finally live in a time where IE9 support is not crucial. 

sorry for not being of help here!

**Comment by CapicheDesign** [comment]
Thanks for the response. Yes, in a perfect world we would not have to support IE9, unfortunately that is not the world I live in :) I will keep investigating and report back if and when I figure it out.

**Comment by wstoettinger** [comment]
my deepest condolences that you have to support IE9! Have you figured out something yet?
