### ISSUE TITLE
Parallax design in responsive mode

### ISSUE THREAD

**Issue by miowebdesigns** [pixelcog/parallax.js#239]
I really like your simplistic approach to creating a parallax page but I have one issue, it does not work on mobile devices. Have you figured out how to make it work on a mobile device? This is the best looking most versatile solution with that one issue. LMK
Michael

**Comment by wstoettinger** [comment]
Hey Michael,

have you checked out pull request #223 ? I have not had time yet, to merge it with the main branch.

Best
Wolfgang

**Comment by wstoettinger** [comment]
any news?
