### ISSUE TITLE
Parallax mirror not moving on scroll

### ISSUE THREAD

**Issue by stevenbhn** [pixelcog/parallax.js#242]
Hi,
I've developed a WordPress theme that takes advantage of the Parallax script you have developed. 

One user has complained that it's broken on their site. I've investigated so much but can't figure out whats going on. When the user scrolls down the page the header parallax mirror stays in position. I would expect the CSS top: position to change with the scroll.

Here is the broken site: 
http://cook-connect.com/

Here it is working on my demo site:
http://demos.templateexpress.com/food-express/

I have changed the broken site to use v1.5 to see if that would fix the issue.

Can you please spare a few secs to have a look and point me in the right direction. 
Thanks
Steven

**Comment by wstoettinger** [comment]
hmm ... on the broken site the parallax is not used correctly. The image is set directly as background and not via the correct data-attributes:
````html
data-parallax="scroll" data-image-src="..."
```

Could you check, if it is the right version of the template and if the same header element with parallax effect is used?

**Comment by luminalpark** [comment]
Hi,
here you can see a similar problem, the parallax mirror is not moving while scrolling, only if the window size is <800px.

[http://staging.luminalpark.it/landing/vintage](http://staging.luminalpark.it/landing/vintage)

Can you help me finding the cause?

Thanks

Carlo

**Comment by wstoettinger** [comment]
@luminalpark i cannot reproduce your issue. it seems to work fine now (at least on my browser). if you are still experiencing issues, please open a new issue or turn to stackoverflow for help.
