### ISSUE TITLE
Should the example from the 2.0 alpha work?

### ISSUE THREAD

**Issue by burzum** [pixelcog/parallax.js#243]
I've copy and pasted it and ran the JS in the console nothing happened. Tried to put it into a file just to be sure - didn't work either. The image simply disappears and the area is white. And the markup looks like that after the script was executed:

![image](https://user-images.githubusercontent.com/162789/35654608-2f6727e0-06ee-11e8-885c-cb0f89497c9b.png)

```html
<div class="my-parallax-window">
  <div class="my-parallax-slider">
    <img src="img/parallax/werratalsee.jpg"/>
    <p>This content and the image will move when scrolling</p>
  </div>
  <div class="some-optional-fixed-content">
    <p>This content will stay in place</p>
  </div>
</div>
```

```css
.my-parallax-window {
    min-height: 700px;
    background: transparent;
}
```

```js
$('.my-parallax-window').parallax({
  speed: -.2,
  sliderSelector: '>.my-parallax-slider',
})
```

**Comment by wstoettinger** [comment]
Hey! 
sorry for my late response! Did you figure it out yet? please make sure that all elements in front of the body have a transparent background so nothing gets into the way of the parallax element.

best
Wolfgang

**Comment by burzum** [comment]
Good morning Wolfgang, better late than never. ;) 

I'could't get it to work and found another solution that worked for me but I might drop the whole parallax thing because it has issues on mobile browser, no matter what solution I'm using. :(

**Comment by wstoettinger** [comment]
for mobile support check pull request #223 
unfortunately i have not had time yet to look at it and merge it.

i will close this issue now since you are not pursuing it anymore. hope that's ok!
