### ISSUE TITLE
Text Scrolling 

### ISSUE THREAD

**Issue by danhanee** [pixelcog/parallax.js#245]
Is there a way to make the text in front of an image have the same parallax effect? Great plugin!!

**Comment by wstoettinger** [comment]
Hey @danhanee ,

sure! you just have to put the text inside the `.parallax-slider` div together with the image.

check this example:
```html
<div class="parallax-window">
  <div class="parallax-slider">
    <img src="/path/to/image.jpg" srcset="/path/to/image-400px.jpg 400w, /path/to/image-800px.jpg 800w, /path/to/image-1200px.jpg 1200w" sizes="100vw">
   <p>This text will move with the image</p>
  </div>
</div>
```

```javascript
$('.parallax-window').parallax({
    naturalWidth: 600,
    naturalHeight: 400
  });
```

**Comment by wstoettinger** [comment]
since this is more a question than an issue, i will close it now. hope you are okay with it!
