### ISSUE TITLE
turn this effect off

### ISSUE THREAD

**Issue by aleku666** [pixelcog/parallax.js#248]
Hi. I´ve bought a template containing this parallax script. how do I turn it off? its build in and im not a skilled coder so i would like just to add some atributes to do it. I like how background and front pictures are done. I dont want to cut all script from the code just need to make it kinda static.

**Comment by wstoettinger** [comment]
Hello @aleku666 
please contact the developer of your template/theme as it is impossible to tell how it is implemented, sorry!°
