### ISSUE TITLE
Cant make it work with WordPress Function Reference

### ISSUE THREAD

**Issue by kosvrouvas** [pixelcog/parallax.js#25]
Hi, awesome work, but I'm a bit of a problem implementing it with WordPress function: get the post thumbnail

The code: 

```php
<div class="headerwrap parallax-window" data-parallax="scroll" data-image-src="<?php the_post_thumbnail( $size, $attr ); ?> ">
</div>
```

But doesn't seem to work, anyone know a workaround/fix or even if this is possible?

**Comment by mikegreiling** [comment]
could it have to do with the extra space after `?>` and before the closing quote?

**Comment by NateFlynn** [comment]
I'm also having an issue with using Post Thumbnails in Wordpress.

@kosvrouvas the problem you have is that the_post_thumbnail() returns an image element. You'll need to get the attachment URL of the post thumbnail like so:

$url = wp_get_attachment_url( get_post_thumbnail_id( $post->ID ) );

<div class="headerwrap parallax-window" data-parallax="scroll" data-image-src="<?php echo $url; ?>"></div>

Hope that helps.

Unfortunately for me the image isn't getting added to the body tag in my document at all. It has worked fine for me previously but now using data attributes there's nothing being added.

**Comment by kosvrouvas** [comment]
No, @NateFlynn still can't get it work... Thank you though!

**Comment by NateFlynn** [comment]
@kosvrouvas did you echo the value of $url into the data-image-src attribute? It may return as an array so if that doesn't work try echo $url[0] instead.

ie:

```
$url = wp_get_attachment_url( get_post_thumbnail_id( $post->ID ) );

<div class="headerwrap parallax-window" data-parallax="scroll" data-image-src="<?php echo $url; ?> ">
</div>
```

or 

```
<div class="headerwrap parallax-window" data-parallax="scroll" data-image-src="<?php echo $url[0]; ?> ">
</div>
```

Hope this one works!

**Comment by mikegreiling** [comment]
I'm not a wordpress user, so I really can't help much on this one, but like @NateFlynn commented, and based on the [WP documentation](http://codex.wordpress.org/Function_Reference/the_post_thumbnail) on `the_post_thumbnail()` it would appear this is returning a full `<img />` tag and not a simple URL.

You'll need to use something like:
```php
<?php
list($src, $width, $height) = wp_get_attachment_image_src(get_post_thumbnail_id(), 'full' );
?>
<div class="headerwrap parallax-window" data-parallax="scroll" data-image-src="<?php echo $src; ?>" data-natural-width="<?php echo $width; ?>" data-natural-height="<?php echo $height; ?>">
```

You may or may not need to add a parameter to the `get_post_thumbnail_id()` function.  I don't really know how it works in this context and of course, I cannot test this since I don't have a wordpress site to mess around with, but this is based on the documentation found here:
http://codex.wordpress.org/Function_Reference/wp_get_attachment_image_src

**Comment by casikr** [comment]
Hi, this works for me on Wordpress
$post_thumbnail_id = get_post_thumbnail_id();
$to = wp_get_attachment_thumb_url( $post_thumbnail_id );

and then
<?php 					
if(has_post_thumbnail()) {
echo '<div class="parallax-window" data-parallax="scroll" data-position="center top" data-image-src="' . $to . '"></div>'; } ?>

**Comment by kosvrouvas** [comment]
Ηι, what @NateFlynn worked! Thanks! Haven't tested @mikegreiling's answer but good to know, thank you too!

**Comment by mikegreiling** [comment]
glad to hear it

**Comment by NateFlynn** [comment]
@kosvrouvas glad you got it working!

In other news, mine's also working now as well... turns out it was a bug in my minification script causing parallax to be called before jQuery.... doh!
