### ISSUE TITLE
Conflict with mootools

### ISSUE THREAD

**Issue by rom08** [pixelcog/parallax.js#251]
Hi
I am using the parallax 1.5.0., Joomla 3.8.6
I'm having a problem with the parallax plugin. After the first page loading, the parallax effect works fine. If you reload the page, it starts to work incorrectly, besides, the anchors on the page become non-clickable and some scripts stop working. If you disable mootools, the parallax effect works fine together with other plugins, but I need mootools for photo gallery work. 
I tried to use jQuery.noConflict(), but it did not help.

How to fix the conflict of the plugin with mootools?
Here my site
https://zkovka.ru/katalog/kovanye-balkony.html

Best regards, Roman

**Comment by wstoettinger** [comment]
Hey Roman,
your link unfortunately doesn't work. It also seems that this issue is not a problem with this plugin but with mootools. I would suggest you post this problem on stackoverflow to find help as this issue tracker is not a support forum!

thanks for your understanding!
