### ISSUE TITLE
warning on https

### ISSUE THREAD

**Issue by williamsherlock** [pixelcog/parallax.js#256]
when i call it on a class i get this warning on my https server. what can i do to fix it?

Mixed Content: The page at 'https://djenee.com/' was loaded over HTTPS, but requested an insecure image 'http://appon.io/'. This content should also be served over HTTPS.

**Comment by nickmak** [comment]
I don't believe this is relevant to the plugin. I wasn't able to see any reference to `http://appon.io/` loaded in any of the 2.x or 1.x scripts. This might be something else related on your site.

**Comment by williamsherlock** [comment]
i don't know why its happened but now i have fixed id the plugin return the undefined value from js, at line number #150 
if (!sliderExisted)
    {
      if(typeof this.imageSrc !== "undefined")
        this.$slider[0].src = this.imageSrc;
    }

Instead of this:
if (!sliderExisted)
   this.$slider[0].src = this.imageSrc;

**Comment by wstoettinger** [comment]
this is not an error in the plugin. you are probably using an http url for the image on an https page. try omitting the protocol in the link so the browser automatically uses the right one
Change `data-image-src="http://appon.io/your-image.jpg"` to `data-image-src="//appon.io/your-image.jpg"`

i hope this helps!

**Comment by wstoettinger** [comment]
I'd kindly ask you to use stackoverflow for non-related questions like this in the future.
