### ISSUE TITLE
Attempting to Pair with Animsition

### ISSUE THREAD

**Issue by dronettdevin** [pixelcog/parallax.js#27]
Hi, this is an awesome plugin and is working great, it's the best one I have found.
I am fairly new at using jQuery and was wondering if its a possibility to pair it with an Animsition fade.

Basically, when the page loads, the parallax images load instantly and all my other html/css elements fade on top and it is not a seamless transition. Is there someway to delay the loading of the parallax images or a least make it not instantaneous. 

Its probably a stretch and may be hard to implement but any help is welcome, thanks.

source: http://git.blivesta.com/animsition/

**Comment by dronettdevin** [comment]
Sorry for the trouble(I'm dumb), your parallax plugin is the greatest. Instead of enclosing all of my elements in a div inside the body with the class "animsition" I gave my body tag the class "animsition" and it works flawlessly.

**Comment by mikegreiling** [comment]
Glad to hear you figured it out.
