### ISSUE TITLE
not working in IE 11?

### ISSUE THREAD

**Issue by petersinot** [pixelcog/parallax.js#28]
Hello
I tryed the script and it is working in chrome. But in IE11 the first time it is not working (you don't see any picture) when you reload the page. then you see the pictures. if you clear the browser historie and cache, then again.

http://heidyhappykids.nl/

thanks peter

**Comment by petersinot** [comment]
the demo site is working on IE11. but i don't understand whats the problem.

**Comment by nealmckinney** [comment]
Try adding the data-natural-width & data-natural-height attributes to your div, fixed the issue for me on Browserstack for IE11.

**Comment by mikegreiling** [comment]
I just visited your website in IE11 and it appears to be working correctly.  Did @nealmckinney's suggestion help you?

If you are still experiencing problems, let me know and I can reopen the issue.
