### ISSUE TITLE
Static image on Android shows nothing

### ISSUE THREAD

**Issue by alfredvaa** [pixelcog/parallax.js#29]
While the parallax effect works perfectly on the desktop version of the web page, it shows nothing on a mobile device (Android, Samsung Galaxy S3). The plugin is used within a Wordpress theme.

As I understand, the images should be viewed as static if no settings are passed. Passing setting androidFix to either true or false does not change the outcome.

**Comment by mikegreiling** [comment]
Since you closed the issue I'm assuming you solved the problem on your own?

**Comment by alfredvaa** [comment]
Yes, it was another not related mistake that I had done...
