### ISSUE TITLE
overflow: auto; not smooth animation

### ISSUE THREAD

**Issue by SaadShahd** [pixelcog/parallax.js#30]
the animation becomes not smooth
when the body,html tags having overflow: auto; and height:100% css properties

**Comment by mikegreiling** [comment]
do you have an example hosted someplace that I could take a look at it?

**Comment by SaadShahd** [comment]
in this fiddle i think it's not having the right implementation:
http://jsfiddle.net/L52Ldnpb/

**Comment by mikegreiling** [comment]
Ah, I see what you mean now.  Unfortunately, I cannot think of a quick fix for this.

This script is hard-coded to use `$(window).scrollTop()` when calculating the current scroll position, and using `overflow: auto;` on the html and body elements breaks this.  You could attempt to modify parallax.js to use `$("body").scrollTop()` instead, and perhaps that will fit your needs.

An option to use a different base element like this may appear in a future version, but for now you are on your own.
