### ISSUE TITLE
Does not work with Angular Universal

### ISSUE THREAD

**Issue by Liudmyla01** [pixelcog/parallax.js#302]
Hello! I'm using Angular Universal (SSR) for SEO and after compiling have a problem :
ERROR TypeError: Cannot read properties of null (reading 'indexOf')
<img width="1198" alt="Screenshot 2022-05-10 at 11 55 46" src="https://user-images.githubusercontent.com/74067187/167590141-62be6578-1bda-4c10-8b90-0b34cbc87f20.png">

**Comment by wstoettinger** [comment]
Hi @Liudmyla01, 
unfortunately Angular is not supported for this library. I am also not familiar enough with angular to implement support for it. Also there is not much information in the error message related to this library. how did you import it?

**Comment by Liudmyla01** [comment]
@wstoettinger Hi, sorry I got it wrong!
