### ISSUE TITLE
Question on Positioning

### ISSUE THREAD

**Issue by darknailblue** [pixelcog/parallax.js#32]
Hi!

I'm working on a site right now and seem to be running into a pitfall with the positioning.  If you look at http://globalsteeringsystems.asquaredhosting.com/global-steering/ and size the browser down (more towards a mobile width) the background images end up not extending 100% to the right.  I've uploaded some pretty big images too over 5k in with and 2k in height.

Am I doing something wrong?  Is this a bug?  Please let me know.

**Comment by mikegreiling** [comment]
After playing around with your website in the chrome developer console, it seems that the `img { max-width: 100% }` declaration is what is throwing it off.  Also, the `body { height: 100% }` with a white background was partly obscuring the parallax images when I checked it out in Safari until I changed the z-index value of the parallax sliders.

I'll update the plugin to explicitly declare the max-width in a future patch, but for now you should be able to fix the issue with the following CSS:

```css
img.parallax-slider {
   max-width: none;
} 
```

**Comment by darknailblue** [comment]
okay awesome.  Thanks so much.  I love this thing!
