### ISSUE TITLE
Prevent img load for non displayed elements

### ISSUE THREAD

**Issue by ivyowl** [pixelcog/parallax.js#36]
Essentially i'm just trying to figure out a way of providing lower res images for smaller screens. I want to use a lower res-static background for everything smaller than a set width,Ideally i'd like to do this with straight CSS, but would be happy to use the inbuilt solution if theres a way of providing lower res images.

Is their anyway to prevent the loading of the image if the window is display:none; for example?
That way i could do the rest with css and the large image isn't going to be loaded.

**Comment by mikegreiling** [comment]
There isn't really a good mechanism for doing this natively if you want a CSS-only solution...  You could try calculating the image src through jQuery as suggested in a few responses to issue #19.

Perhaps sometime in the future, parallax.js will support something like `srcset` for specifying multiple img urls.

**Comment by ivyowl** [comment]
Thanks for the reply - it wasn't quite what i was after but i've found a solution using enquire.js
http://wicky.nillia.ms/enquire.js/
That way i can just initialise the parallax like this then do the rest with css:
enquire.register("screen and (min-width:769px)", function() {
  $('.p-window').parallax({imageSrc: 'p-window.jpg'});
});

**Comment by mikegreiling** [comment]
Glad to hear you got it working.
