### ISSUE TITLE
Height getting set to 0

### ISSUE THREAD

**Issue by ryanscherler** [pixelcog/parallax.js#4]
Any ideas why the script is not setting the height based off the natural height data attribute?

Example: http://arrayhealth-wireframes.pbdhdev.com

I am using bower to pull in the parallax.js dependency and Grunt to compile (jQuery is before the other list of required components), and then minifying the script - which shouldn't be the issue?

**Comment by mikegreiling** [comment]
closing due to lack of response

**Comment by JackFly26** [comment]
I have the same thing.
