### ISSUE TITLE
Performance issues / image flickering

### ISSUE THREAD

**Issue by schuette** [pixelcog/parallax.js#41]
Has anyone noticed issues in Firefox with the images flickering? On the demo page, one of the images may disappear while scrolling. All you see is the white background. When you stop scrolling, the image appears. This only happens occasionally. Sometimes it works totally fine. I can't figure out what is causing it.

I took a [video] (http://cl.ly/image/1s3d2S45053b) to show the issue.

**Comment by mikegreiling** [comment]
Strange, I have not encountered this issue before.  What browser are you using?  Could this be a GPU issue?

**Comment by schuette** [comment]
Firefox... GPU issue is possible, although I’ve seen it happen on my colleagues computer too. He has a new Mac Pro with Thunderbolt display. I’m using 2013 Macbook Pro with retina display.

**Comment by cmarlow** [comment]
I'm having the exact same issue. Using Firefox 35.0.1 on a 2013 MacBook Air. Like schuette described, the background parallax images temporarily disappear, sometimes with horizontal lines streaming across. The images reappear when I stop scrolling. It only happens sometimes.

**Comment by mikegreiling** [comment]
I cannot seem to replicate the issue on either of my machines (using Firefox 35.0 and 36.0.1), but given that it happens only occasionally as you say, it is pretty difficult to diagnose.

You could try taking out some of the GPU hacks by removing the lines that add `translate3d` CSS both [here](https://github.com/pixelcog/parallax.js/blob/6f9b3b3/parallax.js#L226) and [here](https://github.com/pixelcog/parallax.js/blob/6f9b3b3/parallax.js#L235).  Let me know if that does anything for you.

**Comment by cmarlow** [comment]
Thanks so much for getting back to me! My navigation had a fixed position,
so to it, I added:
-webkit-transform: translate3d(0, 0, 0);
transform: translate3d(0, 0, 0);

It seemed to clear up the issue completely! I'm thinking there was some way
that the browser was trying to add the effect to the header.

Thanks again for your time.

**Comment by mikegreiling** [comment]
@schuette did this solve your issue as well?

**Comment by schuette** [comment]
Yes, I've been testing all weekend and haven't noticed the issue anymore, so I think it's safe to say it's fixed. Thanks!

**Comment by mikegreiling** [comment]
Cool, good to hear.
