### ISSUE TITLE
Clash with FLEXSLIDER

### ISSUE THREAD

**Issue by mrandersonsj** [pixelcog/parallax.js#42]
http://lightphorialamp.net/product

Had it working perfectly but now it appears to clash when on the same page as flexslider.

my suspicion is that the parrallax initialises and does its page height calculations, then the flexslider loads and changes the page height but parrallax isn't updated with the new page height. Thats why removing the flex slider worked, thats why no css fixes it and thats why a small window adjustment fixes it because there is a onresize tied to it. We just have to force it post flexslider

**Comment by mikegreiling** [comment]
```javascript
jQuery(window).trigger('resize').trigger('scroll')
```

see issue #34 and the notes section of README.md
