### ISSUE TITLE
Feature Request: Set class for .parallax-mirror

### ISSUE THREAD

**Issue by DArtagan** [pixelcog/parallax.js#44]
It would be great if while setting `<div data-parallax="scroll" data-image-src="/path/to/image.jpg"></div>`, one could also set `data-class="classy_image"`.  This would append `classy_image` to the class of the fixed position element, making something like: `<div class="parallax-mirror classy_image" ...><img src="... /></div>`.  Then, one could access and style the images themselves - adding filters, opacity, etc.

**Comment by gyduxa** [comment]
I did this.

Right after
`this.$slider=t("<img />").prependTo(this.$mirror),this.$mirror.addClass("parallax-mirror")`

I've appended:
`.addClass(h.className)`

So, it would be something like this:
(...)
`this.$slider=t("<img />").prependTo(this.$mirror),this.$mirror.addClass("parallax-mirror").addClass(h.className).css({visibility:"hidden"` (...)


In the HTML just add the same name with hifens:
`data-class-name="something"`


It works for me. Hope it helps

**Comment by DArtagan** [comment]
Very nifty, thanks @gyduxa.
