### ISSUE TITLE
parallax stuttering in IE on scroll

### ISSUE THREAD

**Issue by d3lve** [pixelcog/parallax.js#48]
Hi, great piece of script! However I'm having an issue in IE. Version 10 and 9 the parallax stutters when scrolling up and down.  Is there a fix for this or can it be switched off for IE?

**Comment by wstoettinger** [comment]
there has recently been merged a performance improvement, please check it out!
closed antiquated issue for cleanup. if this is still rellevant, feel free to reopen.
