### ISSUE TITLE
Edit options dynamically

### ISSUE THREAD

**Issue by Krakabek** [pixelcog/parallax.js#51]
Is it possible to edit options after first initializing parallax on elements?

Like I initialize parallax on element by

``` javascript
          $('.my-window').parallax({
            imageSrc: 'img/background.jpg',
            speed:0.1,
          });
```

And then I would like to disable parallax (for example, after clicking on button 'disable-parallax')

``` javascript
$('.disable-parallax').click(function(){
   $('.my-window').parallax({
       speed:1,
   });
}
```

So, is it possible?

**Comment by wstoettinger** [comment]
closed antiquated issue for cleanup. if this is still rellevant, feel free to reopen.
