### ISSUE TITLE
Repeating pattern sizing

### ISSUE THREAD

**Issue by vanadisv** [pixelcog/parallax.js#52]
Hello!

I was experimenting with some repeating background patterns and currently, the pattern image is just blown up in size to create room for the parallax effect.

I was wondering if there is any way to have parallax effect using a repeating pattern as the background?

**Comment by orangepineapple** [comment]
I was able to make a repeated background work by using the slider feature.

Create an empty slider:

`<div class="parallax-window">
    <div class="parallax-slider"></div>
</div>`

Then add your repeating background to .parallax-slider:

`.parallax-slider {
    background: url({pattern.png});
}`

Initialize and viola:

`$('.parallax-window').parallax({
    naturalWidth: 600,
    naturalHeight: 400
  });`
