### ISSUE TITLE
Conflict with CSS3 transtion effect

### ISSUE THREAD

**Issue by miladrahimi** [pixelcog/parallax.js#57]
Please add following css properties to your project somehow:

```
.parallax-mirror, .parallax-mirror * {
    transition: none;
}
```

**Comment by ezhlobo** [comment]
Transition property is [empty by default](http://www.w3.org/TR/css3-transitions/#transition-shorthand-property). If you need to reset transitions in your application, you should do it in your application. Am I wrong?

**Comment by miladrahimi** [comment]
This script doesn't work with any transition so maybe it can be a good idea to set it none in any situation.

**Comment by wstoettinger** [comment]
closed antiquated issue for cleanup. if this is still rellevant, feel free to reopen.
