### ISSUE TITLE
How to show content into the parallaxed div?

### ISSUE THREAD

**Issue by miladrahimi** [pixelcog/parallax.js#58]
How to show content into the parallaxed div?
I had a parallaxed image and i wanna put some text there on it.

**Comment by januarycreative** [comment]
<section data-parallax="scroll" data-image-src="/path/to/img.jpg">
		<div class="content">
			<h1>Page Title</h1>
			<h4>Subheading</h4>
		</div>
    </section>


Of course you can change the `<div class="content">` to whatever class or thing you want, along with the `<h1>` and `<h4>` as well.

**Comment by miladrahimi** [comment]
It doesn't show anything!

**Comment by wstoettinger** [comment]
closed antiquated issue for cleanup. if this is still rellevant, feel free to reopen.
