### ISSUE TITLE
in IE not smooth

### ISSUE THREAD

**Issue by petersinot** [pixelcog/parallax.js#59]
the site: http://pixelcog.github.io/parallax.js/  is working good in IE 9, but my site : www.fecto.nl  is not smooth scrolling. The text is going over the image when scrolling?

Thanks for help.
peter

**Comment by petersinot** [comment]
i already fixed it, i used <section> . This helps

**Comment by bvilina** [comment]
@petersinot , how did you fix this issue?

**Comment by BenjaminBeck** [comment]
I do have the same issue. The text is going over the image when scrolling.

**Comment by mediengaarage** [comment]
I have the same problem, how do you fix it?

**Comment by wstoettinger** [comment]
there has recently been merged a performance improvement, please check it out!
closed antiquated issue for cleanup. if this is still rellevant, feel free to reopen.
