### ISSUE TITLE
Parallax background flickers/moves when another fixed elements is on page

### ISSUE THREAD

**Issue by webpixels** [pixelcog/parallax.js#60]
Hi,

I have a parallax section and a navbar which after scrolling 200px appears as a fixed elements. When it happens, the parallax background moves down with the amount of pixels the navabar has.

I followed all the steps you mentioned in the documentation. Here is a screenshot:
![Screenshot](http://preview.webpixels.ro/parallax-position-problem.PNG) 

Thank you!

**Comment by RedEars** [comment]
I have the same issue. Did you fix it?

**Comment by towfiqi** [comment]
Having the same issue. anyone found any fix for this?

**Comment by suture** [comment]
I'm noticing the same issue.

**Comment by wstoettinger** [comment]
closed antiquated issue for cleanup. if this is still relevant, feel free to reopen.
