### ISSUE TITLE
Conflict with an offcanvas RWD menu script

### ISSUE THREAD

**Issue by januarycreative** [pixelcog/parallax.js#62]
Hello,

I'm running into issues where the images actually disappear when another jQuery thing is triggered on the page, specifically http://mmenu.frebsite.nl/.

Whenever I click to bring the menu out, the parallax image disappears. Then comes back when the menu is gone. The effect is to slide the entire page to the left as the menu appears on the right. I'm sure this entire moving of the entire page is what is messing it up.

I'm not very skilled in jQuery, so I'm not sure what is going on. Any advice or any way to fix this?

Thanks!

**Comment by wstoettinger** [comment]
closing for cleanup purposes. feel free to reopen if this issue is still relevant.
