### ISSUE TITLE
Bad performance on Safari

### ISSUE THREAD

**Issue by LazyRecon** [pixelcog/parallax.js#63]
Hi everybody.
I have a lot of performance issue on safari, the plugin works fine on chrome and firefox, but on safari is really bad.
I have followed all guidelines and i tryed to load smaller image without any improvement, somebody can tell me why?
the website is here http://delgarda.lstage.g2k.it/

**Comment by othree** [comment]
Hi, I have a small patch for Safari
If you are willing to test.

https://github.com/othree/parallax.js/blob/master/parallax.js

**Comment by TimonVS** [comment]
@othree I can confirm that this doesn't fix the bad performance on Safari.

**Comment by wstoettinger** [comment]
there has recently been merged a performance improvement, please check it out!
closed antiquated issue for cleanup. if this is still relevant, feel free to reopen.
