### ISSUE TITLE
White margin above Parallax-window on large screen

### ISSUE THREAD

**Issue by meesfrenkelfrank** [pixelcog/parallax.js#64]
On my desktop it works fine, but on a large desktop screen i get a strange white margin above the Parallax-window (see attachme
![parallax-no-good](https://cloud.githubusercontent.com/assets/9348206/7725299/9a8b7dfa-fef9-11e4-8014-add1c6d89d39.png)
nt)? Have a look at my test site: http://www.meesfrenkelfrank.com/magento/en/

Any idea whats happening?

Thanks!

**Comment by leMich** [comment]
Hi, i got the same problem on first page load, the first image has a blank top margin, and when i resize the window it's ok !

**Comment by cloudstudio** [comment]
Solution ?

**Comment by wstoettinger** [comment]
to manually refresh the parallax, please use:
```javascript
$(window).trigger('resize').trigger('scroll');
```
