### ISSUE TITLE
When the parallax-window moves, its image doesn't

### ISSUE THREAD

**Issue by spackmat** [pixelcog/parallax.js#65]
Hi,

I have a page with some dynamic content boxes, which slide down and up and change the positions of the parallax windows down the page. This moves away the windows from their parallax background-images.

Is there a way to trigger parallax.js to update the positions of the parallax images as at first page load?

Greets,
Gregor

**Comment by spackmat** [comment]
Hi, I found a workaround for this. When the animation is ready, I trigger a resize event on the window-object, which causes parallax.js to update:

    $(window).trigger('resize.px.parallax')

In general it would be cool, if parallax could register a page length change and trigger an update by itself.

**Comment by TomVDH** [comment]
Could you elaborate and provide a small example?

**Comment by spackmat** [comment]
You should reproduce it with every page using parallax.js by changing the height of an element above a parallax element with the Dev-Tools, for example the header of a page. This moves all subsequent elements in the page flow, but the parallax elements keep their position, until you resize the browser window or trigger a resize event.

**Comment by wstoettinger** [comment]
using `$(window).trigger('resize').trigger('scroll');` should do the trick.
