### ISSUE TITLE
iosFix / androidFix: background-attachement: scroll

### ISSUE THREAD

**Issue by maki3000** [pixelcog/parallax.js#66]
Hello! THX for this plugIn!
For the iosFix and androidFix: did you consider to also set background-attachement to scroll, as almost every touch-device doesn't understand background-attachement fixed?

**Comment by WebbySmart** [comment]
I was wondering why this script does't work on mobile devices. I am using Nexus 4 and the Parallax effect does not happen. Any help?

**Comment by wstoettinger** [comment]
mobile is currently not supported but might get some attention in the future. check #184 for further information.
