### ISSUE TITLE
Mobile No Effect

### ISSUE THREAD

**Issue by WebbySmart** [pixelcog/parallax.js#67]
Does this Parallax work on mobile phones? I can't seem to get the script to work on my Android. Any help appreciated. Works on Desktop.

**Comment by mikegreiling** [comment]
Sorry, no.  This plugin will not work on mobile devices.  iOS and Android browsers do not have the necessary scroll event handling to make it work.

**Comment by WebbySmart** [comment]
OK thanks Mike.

**Comment by phanthinh** [comment]
@mikegreiling @WebbySmart 

Thank for lib very use. About this issue i think we should remove lines code below

    if (navigator.userAgent.match(/(iPod|iPhone|iPad)/)) {
      if (this.imageSrc && this.iosFix && !this.$element.is('img')) {
        this.$element.css({
          backgroundImage: 'url(' + this.imageSrc + ')',
          backgroundSize: 'cover',
          backgroundPosition: this.position
        });
      }
      return this;
    }

    if (navigator.userAgent.match(/(Android)/)) {
      if (this.imageSrc && this.androidFix && !this.$element.is('img')) {
        this.$element.css({
          backgroundImage: 'url(' + this.imageSrc + ')',
          backgroundSize: 'cover',
          backgroundPosition: this.position
        });
      }
      return this;
    }

I'm removed it and work fine at my project. What do you think about this? 

Best regards

**Comment by 24Degrees** [comment]
@phanthinh: did you actually forked your solution and is it working? Sounds nice to have this library working on mobile devices.

**Comment by gerrgg** [comment]
@phanthinh solution worked for me, thanks!
