### ISSUE TITLE
Change parallax image

### ISSUE THREAD

**Issue by s-oehding** [pixelcog/parallax.js#68]
Hi,

Is it possible to retrigger the creation of the prrallax-mirror element? I try to change the parallax image after the user clicked a link. I currently tried to update the "data-image-src" but after successfully updating it the image in the .parallax-mirroro element doesent changed.

**Comment by artifactdev** [comment]
I have the same issue

**Comment by kevin93w** [comment]
You can use jQuery or javascript to update the source of the image inside the mirror, something like:

`$(.parallax-slider).attr('src', 'images/new-image.png');`

**Comment by arnisjuraga** [comment]
But if I have multiple images on one page? Can I add some data attribute, or class for each image, so they can be access directly afterwards?

w.g. access by index number: 

`$('.parallax-slider').eq(3).attr('src', 'some/image.jpg')`

But images are loaded in reverse order and I cant be sure, which one I am changing.

**Comment by wstoettinger** [comment]
one solution would be to use the "complex html version" and give the individual images an id and access them with jquery via the id like so:
```html
<div class="parallax-window">
  <div class="parallax-slider">
    <img id="slider-image-1" src="some-img.png">
  </div>
</div>
```
```javascript
$('#slider-image-1').attr('src', 'images/new-image.png');
```
