### ISSUE TITLE
Implementing with Rails' Asset Pipeline

### ISSUE THREAD

**Issue by pjc191** [pixelcog/parallax.js#72]
More of a question than an issue:
How should I go about implementing parallax.js through Ruby on Rails' asset pipeline? Images don't seem to be recognized when they are in app/assets/images. 

The div attribute syntax, data-image-src="xyz.jpg", produces < img class="parallax-slider" src="xyz.jpg"> in the browser.
This might be where the error occurs since Rails' asset pipeline wants <%= image_tag "xyz.jpg" %> instead. I don't know how to alter it without messing with the logic of parallax.js.

**Comment by ezhlobo** [comment]
@pjc191 you can also use data-* attributes with [image_tag helper](http://api.rubyonrails.org/classes/ActionView/Helpers/AssetTagHelper.html#method-i-image_tag):

```
= image_tag "", data: {"ping" => "pong", "foo" => "bar"}
```
```
<img src="" data-ping="pong" data-foo="bar">
```

But actually you should not use `image_tag` helper for use parallax.js in rails.

Problem with your code (`data-image-src="xyz.jpg"`) is that Asset Pipeline don't resolve path to image correctly. For do it rails provide [image_path helper](http://api.rubyonrails.org/classes/ActionView/Helpers/AssetUrlHelper.html#method-i-image_path).

Try this:
```
<div class="parallax-window" data-parallax="scroll" data-image-src=<%= image_path("xyz.jpg") %></div>
```

**Comment by chrise86** [comment]
You could use:

    = content_tag :div, nil, class: "parallax-window", data: { parallax: "scroll", "image-src" => image_path("xyz.jpg") }
