### ISSUE TITLE
Internet explorer is buggy/jerky

### ISSUE THREAD

**Issue by BohemMedia** [pixelcog/parallax.js#73]
In internet explorer the parallax effect is quite jerky. It may be better to actually fix this issue, but until then =>

Currently fixed this in my application by duplicating the ios/android fix:

inserted at line 116:
    if (navigator.userAgent.match(/(Trident|MSIE)/)) {
      if (this.msieFix && !this.$element.is('img')) {
        this.$element.css({
          backgroundImage: 'url(' + this.imageSrc + ')',
          backgroundSize: 'cover',
          backgroundPosition: this.position
        });
      }
      return this;
    }

from line 163:
  $.extend(Parallax.prototype, {
    speed:    0.2,
    bleed:    0,
    zIndex:   -100,
    iosFix:   true,
    androidFix: true,
    msieFix:   true,
    position: 'center',
    overScrollFix: false,
...

**Comment by gitmx** [comment]
Thanks for that! :)

**Comment by josephbona** [comment]
Awesome. Fixed for me on IE.
Thank you

**Comment by zhrance** [comment]
@BohemMedia really well done. Thanks for the fix!

**Comment by zhrance** [comment]
I noticed I celebrated too early... it seems that the parallax effect doesn't work anymore in IE now with this modification. Do you experience the same? Would love to hear.

**Comment by rain2o** [comment]
Worked just fine for me! Nice simple solution to IE's lack of capabilities.

**Comment by CapucineDF** [comment]
Thanks, the images are indeed appearing now!
However the parallax effect was buggy on the first image, and just dodn't happen on the following ones, so I changed the fix at line 116 for
if (navigator.userAgent.match(/(Trident|MSIE)/)) {
if (this.msieFix && !this.$element.is('img')) {
this.$element.css({
backgroundImage: 'url(' + this.imageSrc + ')',
backgroundSize: 'cover',
backgroundAttachment: 'fixed',
backgroundPosition: this.position
});
}
return this;
}

Now it works perfectly!

**Comment by CapucineDF** [comment]
Also, part of the problem of the background jerking can be linked to the bug with Windows 8 and Internet Explorer, enabling the smooth scrolling with makes any background-image with background-attachment: fixed jerky when using the mousewheel. 

As advised on another forum, I used 
<script>
 if(navigator.userAgent.match(/MSIE/i) || navigator.userAgent.match(/Trident\/7\./) || navigator.userAgent.match(/Edge\/12\./)) {
				$('body').on("mousewheel", function () {
				  event.preventDefault();
				  var wd = event.wheelDelta;
				  var csp = window.pageYOffset;
				  window.scrollTo(0, csp - wd);
				});
 }
</script>
to fix that and it seems to be working nicely.

**Comment by CapucineDF** [comment]
<script>
 if(navigator.userAgent.match(/MSIE/i) || navigator.userAgent.match(/Trident\/7\./) || navigator.userAgent.match(/Edge\/12\./)) {
$('body').on("mousewheel", function () {
 event.preventDefault();
var wd = event.wheelDelta;
var csp = window.pageYOffset;
window.scrollTo(0, csp - wd);
});
}
</script>

**Comment by jepz88** [comment]
Awesome, thanks for this solution! :)

**Comment by nickpolet** [comment]
Would be nice to see the simple solution from @BohemMedia added to the repo. Internet explorer just doesn't play well at all with this. This solution is an elegant way of **not** adding parallax to IE.

**Comment by davinma** [comment]
@BohemMedia Maybe this will be better:
`````
if (document.all) {
 //something here
}
`````
than yours:
`````
if (navigator.userAgent.match(/(Trident|MSIE)/)) {
 //something here
}
`````
It works well to Microsoft Edge, and fixed background image well on excluding IES(such as IE7-IE10).

In short, 3Q very much:)

**Comment by wstoettinger** [comment]
performance improvements have been merged recently. please check again and reopen if still relevant!
