### ISSUE TITLE
Invisible when image is it at the top

### ISSUE THREAD

**Issue by Buom01** [pixelcog/parallax.js#75]
![capture du 2015-07-09 01 23 54](https://cloud.githubusercontent.com/assets/1537208/8584869/9bebe87a-25db-11e5-9528-80c9e681f9be.png)
![capture du 2015-07-09 01 24 09](https://cloud.githubusercontent.com/assets/1537208/8584870/9bf4e006-25db-11e5-985b-b45cfbc39728.png)

This probleme doesn't appear each time, the parallax image doesn't show when Y scroll position is at 0, generally when the parallax method is called after a local redirection.

My temporary solution is to call $(window).resize() after the loading of image. Note that I have a one page app with [Meteor](https://www.meteor.com).

**Comment by DerBeni** [comment]
...have you tried using data atrributes for naturalWidth, naturalHeight, bleed and speed? ...worked for me.

**Comment by JLNNN** [comment]
using 

```javascript
window.setTimeout(function() {
    $(window).trigger('resize.px.parallax');
}, 100);
```

worked for me :)

**Comment by mikegreiling** [comment]
This is likely because the height of your element was determined after the parallax script had been initially run.  Is that content in the left column dynamically generated?  If it has a way to hook a callback method post-render, you can do the `$(window).trigger('resize.px.parallax');` there.

**Comment by wstoettinger** [comment]
please check the readme for refreshing.
