### ISSUE TITLE
Parallax not work

### ISSUE THREAD

**Issue by Valentyn-Kubrak** [pixelcog/parallax.js#76]
I added this lib like in example after jquery, and it not works!!!

I have div with right class and right height, and I see that background position  changes in element style but in DOM I can not find element with class "parallax-mirror" where should be image.

**Comment by Valentyn-Kubrak** [comment]
It happens in magento on homepage

**Comment by Valentyn-Kubrak** [comment]
It not working with this:

 Plugin: jQuery Parallax
Version 1.1.3
Author: Ian Lunn
Twitter: @IanLunn
Author URL: http://www.ianlunn.co.uk/
Plugin URL: http://www.ianlunn.co.uk/plugins/jquery-parallax/


And no errors. ARGH

**Comment by alex-koepke** [comment]
@Valentyn-Kubrak did you ever resolve the issue?

**Comment by wstoettinger** [comment]
@Valentyn-Kubrak jQuery Parallax from Ian Lunn is a different plugin. Is this your alternative solution now? I do not completely understand your problem. In case you need help to solve it with this plugin, please let me know!
