### ISSUE TITLE
Ability to 'destroy' - remove markup and cleanup event handlers

### ISSUE THREAD

**Issue by extremeandy** [pixelcog/parallax.js#78]
There is currently no API ability to 'destroy' the plugin. This is required for use with frameworks like Meteor.

**Comment by dg55** [comment]
I also need the ability to destroy the plugin. Does anyone know how I might be able to customise the script manually to add destroy methods? Cheers.

**Comment by LOK-Soft** [comment]
see #80

**Comment by wstoettinger** [comment]
has been merged with 410bb4f
