### ISSUE TITLE
Mirror hidden when element is hidden.

### ISSUE THREAD

**Issue by tonicastillo** [pixelcog/parallax.js#83]
Hi. (excuse my english)
In responsive sites I usually use three different elements with different background image sizes. Depends of media size I hide the others two.

Parallax.js don't hide mirror for this hidden elements, and this caused errors.

I have added this code in render event for this works:

```javascript
			if(this.$element.is(':visible')){
				this.$mirror.css({
					display: 'block'
				});
				this.$slider.css({
					display: 'block'
				});
			} else {
				this.$mirror.css({
					display: 'none'
				});
				this.$slider.css({
					display: 'none'
				});
			}

Maybe you can use something like that if you thinks this can help.

**Comment by benjaminpick** [comment]
We have a pull request running for responsive images, you can try it out if you like: #56

**Comment by tonicastillo** [comment]
Perfect!
