### ISSUE TITLE
Kind of a Noob, not sure what I did wrong?

### ISSUE THREAD

**Issue by jeffonyc** [pixelcog/parallax.js#84]
I've loaded my mock-up page to look at:
jeffreyonyc.com/parallax

not sure why my background parallax image wont move?

here is what I have in the doc:
<div class="parallax-container" data-parallax="scroll" data-position="top" data-bleed="10" data-image-src="imgs/patio.png" data-natural-width="1400" data-natural-height="1950"></div> 

IVE ADDED    data-speed="0.2"   but still not moving???

And the CSS:
.parallax-container {
    min-height: 1950px;
    background: transparent;
}

THANK YOU!!!

**Comment by jeffonyc** [comment]
Never mind, I figured it out!   Great plug-in!

**Comment by BakerCo** [comment]
and what was it...
