### ISSUE TITLE
Smooth scroll issue

### ISSUE THREAD

**Issue by pear1** [pixelcog/parallax.js#85]
Hello, 

I like this plugin, but it is not working well with smooth scrolling plugins.
When I scroll to top / bottom of the parallax, image goes out of section for few ms which makes it look bad.

Is anyone having similar issues?
And is there any fix for this issue?

**Comment by waniolka** [comment]
Same here

**Comment by saltict** [comment]
You can change the section after and before this to background-color: #fff to hot fix, I think author should put div parallax in the parent , show we can use overflow !

**Comment by tonisama** [comment]
Same problem here.  Even more noticeable if you have a rgba tint overlay over the section.  The overlay will separate from the image resulting in the user being able to see underneath at a good chunk of the original image.

**Comment by beeeku** [comment]
Hey guys , 
Anyone found a solution or work around it ?

**Comment by waniolka** [comment]
Setting white bg-color for next and previous sections seems to working for me.

**Comment by DrogoNevets** [comment]
add a bleed of 50 pixels, using the configurable options, fixes the issue for me

**Comment by luco** [comment]
+1 here.

**Comment by wstoettinger** [comment]
anyone has an example of this with the latest version? performance improvements have been made, maybe it's fixed now.
