### ISSUE TITLE
parallax & ajax loading

### ISSUE THREAD

**Issue by liangsu1210** [pixelcog/parallax.js#87]
I'm using smoothstate.js for ajax page transitions

first of all, parallax.js only fires when document.ready I've try $('[data-parallax="scroll"]').parallax(); in my ajax callbacks, it will create .parallax-mirror after all, but when I resize the window, it just won't update its positions unless you refresh the page.

anyone can help me? how can I call the function properly so it will work as I refresh it?

thanks in advance:) I know little bit jquery but this thing beyond my knowledge and I've been stuck there for a long time

**Comment by liangsu1210** [comment]
it works in firefox but others not, please anyone can help?

**Comment by WouterSchoofs** [comment]
is this still not fixed?

**Comment by KillTheBronies** [comment]
I know this thread is old as hell but if you're still having the problem you can call <pre>$(window).trigger('resize.px.parallax');</pre> to update the positions.

**Comment by rv888** [comment]
Thanks @KillTheBronies. I am using this within a dynamic loading scroller and your comment saved me time.

**Comment by irriadin** [comment]
Thanks @KaelWD for providing that solution. I'm also trying to implement smoothstate.js.
