### ISSUE TITLE
Can't get image to appear

### ISSUE THREAD

**Issue by compoundeye** [pixelcog/parallax.js#89]
Hello:

I'm sorry but I'm not having any luck getting this to work. After following your instructions, the image isn't even appearing in my parallaxed div element. The page is here:

http://testing004.compoundeyedesign.com/

.. where I'd like my image to appear is in the white box under the video and the under the purple signup box. In that <div> I have this code:

`<div class="row" data-parallax="scroll" data-image-src="/assets/zoom-39777438-3.jpg" style="background: transparent;">`

And in the bottom of the page code — under where the jQuery is called, as recommended — is my parallax script:

`<script src="./index_files/jquery.min.js"></script>
    <script src="/parallax/parallax.js"></script>`

Things I tested:
1. Any errors in the Chrome Dev Tools for calling the image
2. Looking in other browsers to make sure it wasn't just Chrome. 

Any ideas? Thanks in advance. 

Cheers, Russell

**Comment by xEuPhoRiA-** [comment]
Did you ever find a solution? I'm not able to view the images on Firefox but all other browsers are working.

**Comment by compoundeye** [comment]
No, I never did. I just had to give up in the end.

[image: compoundEye] <http://www.compoundeyedesign.com>
*Russell HrachovecCreative Director**T: *+44 (0)20 8123 9576
*M:* +44 (0)7870 702915
*Skype:* compoundeye9 College Road
Brighton
BN2 1JB
United Kingdom[image: Twitter] <https://twitter.com/compoundtweet> [image:
Facebook] <https://www.facebook.com/compoundeyedesign>compoundeyedesign.com
<http://www.compoundeyedesign.com>

**Comment by neovea** [comment]
Hello, same issue here with html attributes or jquery.

**Comment by rbodin** [comment]
i had a similar issue... I finally noticed that if i changed the z-index to a positive value, it would work. Otherwise it would remain hidden behind the body if the body's background is set. In my case i was setting the body background to white, so i didn't really need it, and removed it... and parallax was finally showing images...

Hope this will help...

**Comment by compoundeye** [comment]
@rbodin: Thanks for the update. I'll give that try. :+1:

**Comment by mcdoolz** [comment]
I had this issue and discovered that the parallax-mirror was being hidden by my body elements background colour.  I set the parallax-mirror to a positive z-index and it appears correctly.  I have no idea if this is going to cause problems.
I'm loading the javascript in my footer, and using data attributes.

**Comment by compoundeye** [comment]
@mcdoolz OK, thanks for that. I appreciate the feedback.

**Comment by pranavraghaw** [comment]
@rbodin Can you tell the filename and the line number where [parallax-mirror] is located. I can't find it.

**Comment by pranavraghaw** [comment]
@mcdoolz Can you tell the filename and the line number where [parallax-mirror] is located. I can't find it.

**Comment by breadyluke** [comment]
@compoundeye @neovea @xEuPhoRiA- check out this link , contains the exact solution you are looking for. NOTE- you need to disable popup blocker for content to appear on the page, they do this as an alternative to the Captcha process(to verify you are not a bot).

**Comment by matthewtesterman** [comment]
Unfortunately, I could not get this to work either. The image just would not appear nor any error information. I tried setting this parallax-mirror to have a z-index of 9999 but no success. 

www.cakesnloafs.in/popexp/ is a dead link.

**Comment by mcdoolz** [comment]
Kind of a late reply here, but I wrote the rule myself folks.

@pranavraghaw it's generated by the javascript and populated with the image.

@matthewtesterman did you set !important?

```
.parallax-mirror
  z-index: 300 !important
```

I've been doing this since I first posted about it and have used it with multiple parallax entities on the page with no ill effect.

Thanks for the great work @compoundeye!

**Comment by matthewtesterman** [comment]
Unfortunately, I already had tried that and no luck. I wondered if there were conflicts with other JS libraries I was using such as jQuery UI?  Or Bootstrap? 

Ultimately, I ended up using another parallax plugins and they worked.

**Comment by mcdoolz** [comment]
Which plug in did you end up going with?

**Comment by pranavraghaw** [comment]
The best alternative solution is using the parallax muse widget.

**Comment by morgansegura** [comment]
You can just add: data-image-src to the parallax window yourself, even though it was supposed to be done by the plugin. BTW, mine didn't work without this solution either. Now you can use the other benefits of this plugin. ordering, hover effects, speed etc; here is the code I used

`import $ from 'jquery';
import Parallax from 'parallax-js';

class ParallaxWindow {
    constructor() {
        // Parallax background
        this.container = '.parallax-window';
        this.parallaxInit();
    }

    events() { 

    }

    parallaxInit() {

        $(this.container).each((key, value)=>{
            
            let data = $(this.container).eq(key).data('image-src');
            let speed = $(this.container).eq(key).data('speed');
            let depth = $(this.container).eq(key).data('depth');

            let scene = $(this.container)[0];

            let p = new Parallax(scene, {
                selector: `${this.container}__layer`,
                relativeInput: true,
                imageSrc: data,
                speed: speed !== 'undefined' ? speed : 0.4,
                depth: depth !== 'undefined' ? depth : 0.0,
            });

            // for now the data-image-src isn't working 
            // if they figure it out I will swith to their solution
            // but for now, "The show must go on"

            $(this.container).css({'background-image':`url(${data})`})


            console.log(p);
            console.log(data);
            console.log(speed);
            console.log(depth);
        });
    }

}

export default ParallaxWindow;`

If you need more help please feel free to ask.

Cheers!

**Comment by ninthony** [comment]
@mcdoolz Thanks for the positive z-index comment. Solved my issue.
