### ISSUE TITLE
Publish on NPM ?

### ISSUE THREAD

**Issue by acezard** [pixelcog/parallax.js#91]
I love your plugin and it would be great to easily install it with npm and bundle it with browserify without any hassle.

**Comment by sparkbuzz** [comment]
@mikegreiling @acezard  I second this! I'm not using Bower at all anymore, it would be awesome if you could simply merge this PR to allow NPM package registration! Please!

**Comment by LFeh** [comment]
+1

**Comment by guntherkoo** [comment]
+1

**Comment by adamsheridan** [comment]
+1

**Comment by Rainbowlemon** [comment]
+1

**Comment by piotrkulpinski** [comment]
+1

**Comment by yuchant** [comment]
+1

**Comment by artursopelnik** [comment]
https://www.npmjs.com/package/jquery-parallax.js

**Comment by wstoettinger** [comment]
done
