### ISSUE TITLE
wrong parallax-mirror position on load, fixed

### ISSUE THREAD

**Issue by mjrev** [pixelcog/parallax.js#94]
not long ago for some reason plugin started to render images wrong - `parallax-mirror` had negative top offset. 
i don't know what caused this, but this offset resets to default when i change window size, so
```javascript
$(window).load(function(){
  $(window).resize();
});
```
solved my problem

**Comment by MichaelM84** [comment]
How did you integrate this code? Have the same problem and I'm going nuts.
