### ISSUE TITLE
Doesn't work with carousel/sliders

### ISSUE THREAD

**Issue by jmak35** [pixelcog/parallax.js#98]
Is this possible at all to work with carousels or sliders?

I've tried using 3 slides with parallax effect, but it just doesn't work. Images aren't being displayed properly. I've tried [Slick](http://kenwheeler.github.io/slick/), [Hero Slider](https://codyhouse.co/gem/hero-slider/) but the parallax just doesn't want to play well with them.

Any chance the code can be updated to work with carousels/sliders? Thank you.

**Comment by wstoettinger** [comment]
not yet in the main branch, but have a look at #88 where this is implemented and working with an Owl Slider, but should also work with any other sliders as long as you initialize them in the right order.
