### ISSUE TITLE
Invert effect direction

### ISSUE THREAD

**Issue by luisfontes19** [pixelcog/parallax.js#99]
It would be great if you add an option to invert the direction of the parallax.

when I'm scrolling down, the content of my page and the parallax image are going up... This option would shift the image down instead,

**Comment by mikegreiling** [comment]
I believe this can be achieved by specifying a negative number for `speed`.  Keep in mind, if you're doing this you'll likely want a very tall and narrow image, as it will need to be a bit larger than the window height.
